<?php

use Photobook\Model\DbTable\Covertype;

$this->headTitle('Hochzeitsalbum Beispiele, Muster, Vorlagen | PikPerfect');
$this->headMeta()->appendName('description', 'Stöbere in unseren Beispielen für Hochzeitsfotobücher, um dich für die Gestaltung deines eigenen Hochzeitsalbums inspirieren zu lassen.');
$this->placeholder('bodyClass')->set('photo-album-boxes');
$region = $this->region()->getUserRegion();
?>
<section class="section-img section-img_size-m m-auto">
    <figure style="padding-bottom: calc(500% / 1440 * 100)" class="figure-webp">
        <picture data-priority="0" data-name="luxury-wedding-album-box" data-path="16.0" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/min-luxury-wedding-album-box.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/luxury-wedding-album-box.jpg" alt="Luxus Hochzeitsalbum Box mit Album im Innern">
        </picture>

    </figure>


</section>
<section class="section-text section-text_light-grey section-text_padding">
    <div class="section-text__container section-text_padding">
        <div class="section-text__content">
            <h1 class="section-text__title">Fotobuch Geschenkbox</h1>
            <p>Die Premium Geschenkschachtel von PikPerfect wird in Handarbeit aus hochwertigem Leinen oder Lederimitat hergestellt, passend zum Bucheinband.</p>
        </div>
    </div>
</section>
<div id="no-video"></div>
<section class="section-slider-half">
    <div class="section-slider-half__wrap">
        <div class="section-hero__left">
            <div class="swiper-container section-hero__swiper section-hero__swiper-half">
                <div class="swiper-wrapper">
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="premium-photo-album-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-premium-photo-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/premium-photo-album-box.jpg" alt="Hochwertiges Fotoalbum mit Box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="linen-photo-album-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-linen-photo-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/linen-photo-album-box.jpg" alt="Photo album box in white linen">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="presentation-box-photobook" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-presentation-box-photobook.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/presentation-box-photobook.jpg" alt="Fotoalbum auf High-End Geschenkschachtel">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="wedding-album-presentation-boxes" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-wedding-album-presentation-boxes.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/wedding-album-presentation-boxes.jpg" alt="Women taking wedding album out of white presentation box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="photo-book-presentation-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-photo-book-presentation-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/photo-book-presentation-box.jpg" alt="Women viewing a photo book presentaion box on table">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="wedding-photo-album-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-wedding-photo-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/wedding-photo-album-box.jpg" alt="Acrylglasfotobuch auf Geschenkverpackung">
                            </picture>

                        </figure>


                    </div>
                </div>
                <div class="section-hero__swiper-pagination"></div>
            </div>
            <div thumbsSlider="" class="swiper-container section-hero__tab-activators section-hero__slider-half">
                <div class="swiper-wrapper">
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="premium-photo-album-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-premium-photo-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/premium-photo-album-box.jpg" alt="Hochwertiges Fotoalbum mit Box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="linen-photo-album-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-linen-photo-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/linen-photo-album-box.jpg" alt="Photo album box in white linen">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="presentation-box-photobook" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-presentation-box-photobook.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/presentation-box-photobook.jpg" alt="Fotoalbum auf High-End Geschenkschachtel">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="wedding-album-presentation-boxes" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-wedding-album-presentation-boxes.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/wedding-album-presentation-boxes.jpg" alt="Women taking wedding album out of white presentation box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="photo-book-presentation-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-photo-book-presentation-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/photo-book-presentation-box.jpg" alt="Women viewing a photo book presentaion box on table">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="0" data-name="wedding-photo-album-box" data-path="16.0/premium-box" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/premium-box/min-wedding-photo-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/premium-box/wedding-photo-album-box.jpg" alt="Acrylglasfotobuch auf Geschenkverpackung">
                            </picture>

                        </figure>


                    </div>
                </div>
            </div>
        </div>
        <div class="section-slider-half__context">
            <h2 class="title main-title">Hochzeitsalbum  <span>Geschenkbox</span></h2>
            <p class="section-slider-half__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                                        $this->smallestPrices['premium'],
                                                        $region->iso,
                                                        2,
                                                        $region->symbol
                                                    ); ?></p>
            <p class="text-entered">Die stabile Geschenkverpackung aus Holz ist exklusiv für unser  <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" class="link" target="_blank">Premium Layflat-Album </a> bzw. <a href="<?php echo $this->languageUrl('static-premium-layflat-wedding-albums-') ?>" class="link" target="_blank">Luxus-Hochzeitsalbum</a>erhältlich und mit veganem Leder oder Leinen deiner Wahl bezogen. Alle Premiumalbum Schachteln können mit einer individuellen Prägung versehen werden (zusätzliche Gebühren).</p>
            <div class="section-slider-half__box">
                <h3 class="title">Farben Leinenbox</h3>
                <div class="section-slider-half__box-wrap">
                    <div class="swiper-container swipercolor">
                        <div class="swiper-wrapper">
                            <?php foreach ($this->coverTypeColors[Covertype::$PREMIUM_LINEN] as $coverTypeColor) : ?>
                                <div class="swiper-slide">
                                    <div class="section-slider-half__img selection-album__color" data-title="<?php echo $this->translate($coverTypeColor['name']) ?>">
                                        <div class="color <?php echo $coverTypeColor['color_class'] ?>"></div>
                                    </div>
                                </div>
                            <?php endforeach ?>
                        </div>
                    </div>
                    <div class="swiper-button swiper-button-next swiper-button-next-first"></div>
                    <div class="swiper-button swiper-button-prev swiper-button-prev-first"></div>
                </div>
            </div>
            <div class="section-slider-half__box">
                <h3 class="title">Farben Kunstlederbox</h3>
                <div class="section-slider-half__box-wrap">
                    <div class="swiper-container swipercolorSecond">
                        <div class="swiper-wrapper">
                            <?php foreach ($this->coverTypeColors[Covertype::$PREMIUM_LEATHERETTE] as  $coverTypeColor) : ?>
                                <div class="swiper-slide">
                                    <div class="section-slider-half__img selection-album__color" data-title="<?php echo $this->translate($coverTypeColor['name']) ?>">
                                        <div class="color <?php echo $coverTypeColor['color_class'] ?>"></div>
                                    </div>
                                </div>
                            <?php endforeach ?>
                        </div>
                    </div>
                    <div class="swiper-button swiper-button-next swiper-button-next-second"></div>
                    <div class="swiper-button swiper-button-prev swiper-button-prev-second"></div>
                </div>
            </div>
            <div class="section-slider-half__button">
                <a href="<?php echo $this->languageUrl('upload-photos-') ?>" class="button">ALBUM STARTEN</a>
            </div>
            <div class="section-slider-half__down-text">
                <p>Box im Warenkorb hinzufügen</p>
            </div>
        </div>
    </div>
</section>
<section class="section-slider-half">
    <div class="section-slider-half__wrap">
        <div class="section-hero__left order">
            <div class="swiper-container section-hero__swiper section-hero__swiper-half-second">
                <div class="swiper-wrapper">
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="1" data-name="wedding-photobook-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-wedding-photobook-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/wedding-photobook-box.jpg" alt="Hochzeitsfotoalbum mit Geschenk Box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="family-album-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-family-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/family-album-box.jpg" alt="Familien Fotobuch in schwarzer Box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photobook-presentation-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photobook-presentation-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photobook-presentation-box.jpg" alt="Fotobuch Geschenkschachtel">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photo-book-gift-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photo-book-gift-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photo-book-gift-box.jpg" alt="Frau schaut Fotobuch in Geschenkschachtel an">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photo-book-storage-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photo-book-storage-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photo-book-storage-box.jpg" alt="Frau schaut Fotobuch in GeschenkschachFotobuch Geschenkbox mit Fotobuch Leinen Blautel an">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide section-hero__slide">
                        <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photo-album-book-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photo-album-book-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photo-album-book-box.jpg" alt="Familien Jahresfotobuch in Box aufbewahrt">
                            </picture>

                        </figure>


                    </div>
                </div>
                <div class="section-hero__swiper-pagination"></div>
            </div>
            <div thumbsSlider="" class="swiper-container section-hero__tab-activators section-hero__slider-half-second">
                <div class="swiper-wrapper">
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="wedding-photobook-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-wedding-photobook-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/wedding-photobook-box.jpg" alt="Hochzeitsfotoalbum mit Geschenk Box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="family-album-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-family-album-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/family-album-box.jpg" alt="Familien Fotobuch in schwarzer Box">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photobook-presentation-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photobook-presentation-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photobook-presentation-box.jpg" alt="Fotobuch Geschenkschachtel">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photo-book-gift-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photo-book-gift-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photo-book-gift-box.jpg" alt="Frau schaut Fotobuch in Geschenkschachtel an">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photo-book-storage-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photo-book-storage-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photo-book-storage-box.jpg" alt="Frau schaut Fotobuch in GeschenkschachFotobuch Geschenkbox mit Fotobuch Leinen Blautel an">
                            </picture>

                        </figure>


                    </div>
                    <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                        <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                            <picture data-priority="2" data-name="photo-album-book-box" data-path="16.0/standard" class="picture-webp">
                                <source class="toggle-img--js" srcset="/assets/images/towebp/16.0/standard/min-photo-album-book-box.webp" type="image/webp">
                                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.0/standard/photo-album-book-box.jpg" alt="Familien Jahresfotobuch in Box aufbewahrt">
                            </picture>

                        </figure>


                    </div>
                </div>
            </div>

        </div>
        <div class="section-slider-half__context">
            <h2 class="title main-title">Fotobuch  <span>Geschenkbox</span></h2>
            <p class="section-slider-half__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                                        $this->smallestPrices['photobook'],
                                                        $region->iso,
                                                        2,
                                                        $region->symbol
                                                    ); ?></p>
            <p style="margin-bottom: 24px;">Mit einer PikPerfect Fotobuch Geschenkschachtel verpackst du dein  <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" class="link" target="_blank">Layflat-Echtfotobuch</a> oder  <a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" class="link" target="_blank">Hardcover Fotobuch</a> stilvoll. Die elegante Box aus dicker Pappe und mit mattschwarzer Oberfläche ist die ideale Verpackung für ein Fotobuch.</p>
            <p class="text-entered">Zusätzliche Farben oder individuelle Anpassungen sind bei diesen schwarzen Standard-Fotobuchboxen nicht möglich.</p>
            <div class="section-slider-half__button">
                <a href="<?php echo $this->languageUrl('upload-photos-') ?>" class="button">BUCH STARTEN</a>
            </div>
            <div class="section-slider-half__down-text">
                <p>Box im Warenkorb hinzufügen</p>
            </div>
        </div>
    </div>
</section>
<div class="section-slider-half__bottom-text">
    <p>Unsere Geschenkboxen für Fotobücher und Hochzeitsalben können während der Entwurfsprüfung zum Album hinzugefügt werden, wenn du <a href="<?php echo $this->languageUrl('static-photo-books-') ?>" class="link" target="_blank">  ein Fotobuch online </a>. <span>bestellst. Die Boxen werden nicht separat verkauft. </span></p>
</div>

<?php echo $this->partial('application/partial/why_choose_us', ['color' => 'dignity_gray']) ?>
<?php echo $this->render('partial/quick_chat.phtml'); ?>