<?php
$this->headTitle('Boudoir Books & Boudoir Photo Albums | PikPerfect');
$this->headMeta()->appendName('description', 'A Boudoir Photo Book is unique, personal, and guaranteed to be cherished forever. Choose from our range of premium album and paper options to create the perfect boudoir book.');
$region = $this->region()->getUserRegion();
?>

<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="boudoir-photo-books" data-path="2.12-boudoir-book" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-boudoir-photo-books.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/boudoir-photo-books.jpg" alt="Women posing in boudoir photo book">
                </picture>

            </figure>


        </div>
        <div class="section-hero__content-col section-hero__content-col_blue-dark">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <div class="section-hero__picture section-hero__picture_lace">
                <picture>
                    <source media="(max-width: 500px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">
                    <img src="/assets/images/towebp/2.12-boudoir-book/lace.png" alt="picture lace">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Boudoir Photo Books</h1>
            <p class="section-hero__small">An amazing gift for that special someone who haseverything else but..</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__light button__light_br-none">start now</a>
            <p class="price"><?php echo $this->translate('From') . ' ' . $this->format(
                                    $this->smallestPrices['photobook'],
                                    $region->iso,
                                    2,
                                    $region->symbol
                                ); ?></p>
        </div>
    </div>
</section>
<section class="section-text section-text_padding">
    <div class="section-text__container">
        <div class="section-text__content">
            <p>Perfect as the gift for the groom or your partner, a Boudoir Photo Album is unique, personal, and guaranteed to be cherished forever.</p>
            <p>Our professional Boudoir Album designers will help make an album that is stylish, yet fun. Your privacy is just as important to us, all photos submitted are treated with the sensitivity they deserve.</p>
        </div>
    </div>
</section>
<section class="section-service section-service_big-cards">
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">You Choose</h4>
            <p>Select your preferred photobook type and album design style, upload your photos.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">We Design</h4>
            <p>Our expert photo book designers bring your album to life. Includes unlimited free revisions.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Pay to Print</h4>
            <p>Only pay when you’re 100% <br> satisfied with the design <br> (no commitment to purchase).</p>
        </div>
    </div>
</section>
<section class="section-img section-img_size-m">
    <div class="section-img__container">
        <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="premium-boudoir-photo-books" data-path="2.12-boudoir-book" class="picture-webp">
                <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-premium-boudoir-photo-books.webp" type="image/webp">
                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/premium-boudoir-photo-books.jpg" alt="A premium boudoir photo book laying on a carpet">
            </picture>

        </figure>


    </div>
</section>
<section class="section-img-text">
    <div class="section-img-text__container">
        <div class="section-img-text__wrap">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="Boudoir book with custom designed title">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <h2 class="section-img-text__title">Boudoir Book Ideas</h2>
                    <p>You can choose from a range of different album covers and paper types to create the perfect Boudoir Book. If you’re looking for the very best, we recommend a <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" target="_blank" class="link">Flush Mount Album</a> offering stunning panoramic spreads printed on thick layflat pages. Choose from a range of premium album covers that can be customized to your liking.</p>
                </div>
            </div>
        </div>
        <div class="section-img-text__wrap section-img-text__wrap_order">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="boudoir-photo-album" data-path="2.12-boudoir-book" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-boudoir-photo-album.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/boudoir-photo-album.jpg" alt="Boudoir photo album on fur blanket">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <p>Our <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" class="link" target="_blank">Layflat Photo Albums</a> are one of our most popular options offering great quality at attractive prices. These albums are developed on Fuji photo paper which offers beautiful uninterrupted double page spreads. Available in your choice of vegan leather, linen fabric or photo covers.</p>
                    <div class="section-img-text__button">
                        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button ">start now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-album section-album_size-lx">
    <div class="section-album__container">
        <div class="section-album__entered-wrap">
            <h2 class="section-album__title">Boudoir Album Design Styles</h2>
            <p class="section-album__entered">Every Boudoir Book is designed from scratch, to match your photos and aesthetic. From subtle sophistication to more fun and vibrant styles, your personal album designers will offer you a number of different options and allow you to pick the one/s you like best. All designs include unlimited free revisions, so we make sure the album is perfect before it’s sent to print.</p>
            <p class="section-album__entered"><strong>Nudity Policy:</strong> While we do expect some nudity, we do not print boudoir books that are very explicit or pornographic. Please keep it classy, like a boudoir book should be.</p>
            <p class="section-album__entered section-album__entered_italic">Note: Keeping our customers' privacy in mind, samples below use stock images.</p>
        </div>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan light yellow">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For Your Eyes Only<span>Boudoir Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan gray">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Love you, Always!<span>Boudoir Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan light brown">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For My Husband<span>Boudoir Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan light yellow">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Laced with Love<span>Boudoir Book</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Ready to make a Boudoir Book?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__light section-transition__button section-transition__button_big">start now</a>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
    <div class="section-text__container section-text_big-container">
        <h2 class="section-text__title">How to Make a Boudoir Photo Book</h2>
        <div class="section-text__content">
            <p>Looking for a stunning boudoir album as a gift for a special someone? A boudoir photo book is a collection of intimate photos, artistically designed into a <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" target="_blank" class="link">premium photo book</a>.</p>
            <p>While there can be little to no nudity in the photos, Boudoir photography generally distinguishes itself by focusing on presenting a provocative but playful look that portrays the subject in a sensual way. Intimacy is implied rather than presented through the use of facial expression, suggestive clothing or specific poses.</p>
            <p>PikPerfect’s team of expert album designers will help you put this collection of special photos together into a stunning boudoir book, creating a special keepsake for yourself, or as a gift for someone else.</p>
        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>