<?php
$this->headTitle('Boudoir Fotobuch | Geschenk für Bräutigam | PikPerfect');
$this->headMeta()->appendName('description', 'Ein Boudoir Fotoalbum ist einzigartig, persönlich und wird garantiert für immer geschätzt. Für dich selbst oder als Geschenk von der Braut an den Bräutigam.');
$region = $this->region()->getUserRegion();
?>

<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="boudoir-photo-books" data-path="2.12-boudoir-book" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-boudoir-photo-books.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/boudoir-photo-books.jpg" alt="Frau in Boudoir Fotobuch">
                </picture>

            </figure>


        </div>
        <div class="section-hero__content-col section-hero__content-col_blue-dark">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <div class="section-hero__picture section-hero__picture_lace">
                <picture>
                    <source media="(max-width: 500px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">
                    <img src="/assets/images/towebp/2.12-boudoir-book/lace.png" alt="picture lace">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Fotobuch Boudoir</h1>
            <p class="section-hero__small">Ein Geschenk für den besonderen Menschen, der <br>alles andere schon hat..</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__light button__light_br-none">JETZT ANFANGEN</a>
            <p class="price"><?php echo $this->translate('From') . ' ' . $this->format(
                                    $this->smallestPrices['photobook'],
                                    $region->iso,
                                    2,
                                    $region->symbol
                                ); ?></p>
        </div>
    </div>
</section>
<section class="section-text section-text_padding">
    <div class="section-text__container">
        <div class="section-text__content">
            <p>Ein Boudoir Fotoalbum ist einzigartig, persönlich und wird als Geschenk für Bräutigam oder Partner garantiert für immer geschätzt.</p>
            <p>Unsere professionellen Fotobuch Designer erstellen ein Buch, das stilvoll ist und Freude macht. Deine Privatsphäre ist uns sehr wichtig, alle eingereichten Fotos werden mit der entsprechenden Sensibilität behandelt.</p>
        </div>
    </div>
</section>
<section class="section-service section-service_big-cards">
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">Du wählst</h4>
            <p>Teil uns deinen gewünschten Fotobuchtyp und Albumdesignstil mit und lade deine Fotos hoch.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">Wir gestalten</h4>
            <p>Unsere Fotobuch Designer erwecken dein Album zum Leben. Überarbeitungen inklusive.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Zahle zum Drucken</h4>
            <p>Zahle erst, wenn du 100 % mit dem Design zufrieden bist  <br> (ohne Kaufverpflichtung). </p>
        </div>
    </div>
</section>
<section class="section-img section-img_size-m">
    <div class="section-img__container">
        <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="premium-boudoir-photo-books" data-path="2.12-boudoir-book" class="picture-webp">
                <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-premium-boudoir-photo-books.webp" type="image/webp">
                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/premium-boudoir-photo-books.jpg" alt="Hochwertiges Boudoir Fotoalbum auf Teppich">
            </picture>

        </figure>


    </div>
</section>
<section class="section-img-text">
    <div class="section-img-text__container">
        <div class="section-img-text__wrap">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="Boudoir Fotobuch mit individuell gestaltetem Titel">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <h2 class="section-img-text__title">Boudoir Fotobuch Ideen</h2>
                    <p>Wähle aus einer Reihe verschiedener Albumcover und Papiersorten, um dein Boudoir Fotobuch zu erstellen. Als High-End Option empfehlen wir ein<a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" target="_blank" class="link">Premium Album</a> mit atemberaubenden Panoramaseiten auf dicken Layflat-Seiten. Premium-Albumcover können nach deinen Wünschen angepasst und personalisiert werden.</p>
                </div>
            </div>
        </div>
        <div class="section-img-text__wrap section-img-text__wrap_order">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="boudoir-photo-album" data-path="2.12-boudoir-book" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-boudoir-photo-album.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/boudoir-photo-album.jpg" alt="Boudoir Fotobuch auf Felldecke">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <p>Unsere  <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" class="link" target="_blank">Echtfotobücher </a> sind am beliebtesten, da sie hervorragende Qualität zu attraktiven Preisen bieten. Ihre ununterbrochenen Doppelseiten werden auf Fuji-Fotopapier in Layflat-Bindung entwickelt. Erhältlich mit Fotobuch Einbänden aus veganem Leder oder Leinen mit Prägung oder als Fotocover.</p>
                    <div class="section-img-text__button">
                        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button ">JETZT STARTEN</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-album section-album_size-lx">
    <div class="section-album__container">
        <div class="section-album__entered-wrap">
            <h2 class="section-album__title">Designstile für ein Boudoir Album</h2>
            <p class="section-album__entered">Jedes Fotobuch mit Boudoir Bildern wird von Grund auf neu gestaltet, passend zu deiner Ästhetik. Von subtiler Raffinesse bis hin zu lustigeren und lebendigeren Stilen bietet dir dein persönlicher Albumdesigner verschiedene Optionen. Du wählst einfach die, die dir am besten gefällt. Alle Designs beinhalten unbegrenzte Überarbeitungen, damit dein Album perfekt ist, bevor es in Druck geht.</p>
            <p class="section-album__entered"><strong>Nacktheitsrichtlinie:</strong> Wir drucken keine Boudoir-Bücher, die sehr explizit oder pornographisch sind. Bitte halte es stilvoll.</p>
            <p class="section-album__entered section-album__entered_italic">Hinweis: Um die Privatsphäre unserer Kunden zu gewährleisten, zeigen die folgenden Beispiele Bildagentur-Fotos.</p>
        </div>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan light yellow">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For Your Eyes Only<span>Boudoir Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan gray">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Love you, Always!<span>Boudoir Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan light brown">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For My Husband<span>Boudoir Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="custom-boudoir-books" data-path="2.12-boudoir-book" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.12-boudoir-book/min-custom-boudoir-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.12-boudoir-book/custom-boudoir-books.jpg" alt="album A Man, A Pan & A Plan light yellow">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Laced with Love<span>Boudoir Book</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Jetzt ein Boudoir Fotobuch erstellen?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__light section-transition__button section-transition__button_big">FOTOBUCH ANFANGEN</a>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
    <div class="section-text__container section-text_big-container">
        <h2 class="section-text__title">Ein Boudoir Fotobuch gestalten</h2>
        <div class="section-text__content">
            <p>Ein Boudoir Fotoalbum ist eine Sammlung intimer Fotos, die künstlerisch zu einem <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" target="_blank" class="link">Premium Fotobuch</a>.</p>
            <p>Da die Fotos wenig bis gar keine Nacktheit enthalten, zeichnet sich die Boudoir-Fotografie im Allgemeinen dadurch aus, dass sie einen provokanten aber verspielten Look kreiert, der das Motiv auf sinnliche Weise darstellt. Intimität wird durch Gesichtsausdrücke, anzügliche Kleidung oder bestimmte Posen eher angedeutet als dargestellt.</p>
            <p>Unsere erfahrenen Album-Designern hilft dabei, deine Fotos in einem atemberaubenden Boudoir-Fotoalbum zusammenzustellen, als besonderes Andenken für sich selbst oder als Geschenk für den Bräutigam oder besondere Menschen.</p>
        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>