<?php
$this->headTitle('Stunning Layflat Photo Books & Albums | PikPerfect');
$this->headMeta()->appendName('description', 'The panoramic spreads of a layflat photo book create a visually stunning memento for your most precious memories.');
?>
<section class="section-hero">
    <div class="container">
        <div class="section-hero__grid">
            <div class="section-hero__left">
                <div thumbsSlider="" class="swiper-container section-hero__tab-activators">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="layflat-photo-albums" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-albums.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-albums.jpg" alt="linen blue layflat photo album laying open">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="linen-photo-album-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-linen-photo-album-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/linen-photo-album-cover.jpg" alt="linen photo album covers with embossed titles">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-photo-book" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-book.jpg" alt="couple with baby in open layflat book">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-book-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-book-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-book-cover.jpg" alt="wedding couple on layflat book cover">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="photo-book-presentation-box" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-photo-book-presentation-box.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/photo-book-presentation-box.jpg" alt="layflat book with presentation box">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="position: relative;">
                                <img style="width: 100%; height:auto;" src="/assets/images/hero-tab-toggle-6.jpg" alt="Flush Mount album example">
                                <img style="position: absolute; top:50% ; left:50%; transform: translate(-50%, -50%); pointer-events: none;" src="/assets/images/icons/button_play.svg">
                            </figure>
                        </div>
                    </div>
                </div>
                <div class="swiper-container section-hero__swiper">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-photo-albums" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-albums.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-albums.jpg" alt="linen blue layflat photo album laying open">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="linen-photo-album-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-linen-photo-album-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/linen-photo-album-cover.jpg" alt="linen photo album covers with embossed titles">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="layflat-photo-book" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-book.jpg" alt="couple with baby in open layflat book">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="layflat-book-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-book-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-book-cover.jpg" alt="wedding couple on layflat book cover">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="photo-book-presentation-box" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-photo-book-presentation-box.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/photo-book-presentation-box.jpg" alt="layflat book with presentation box">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide hero-video-slide">
                            <div class="hero-video-slide__preloader">
                                <svg class="hero-video-slide__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
                                    <g fill="none" fill-rule="evenodd">
                                        <g transform="translate(1 1)" stroke-width="2">
                                            <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                                            <path d="M36 18c0-9.94-8.06-18-18-18">
                                                <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                                            </path>
                                        </g>
                                    </g>
                                </svg>
                            </div>

                            <div class="hero-video-slide__item"> <iframe frameborder="0" id="hero-video" src="" data-src="https://player.vimeo.com/video/569983793?background=1" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Layflat Photo Albums | PikPerfect"></iframe>
                            </div>
                        </div>

                    </div>
                    <div class="section-hero__swiper-pagination"></div>
                </div>
            </div>

            <div class="section-hero__right">
                <h1 class="tab__title">Layflat Photo Album</h1>
                <p class="tab__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['layflat'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="stars tab__starts">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <span><?php echo $this->reviewsCount()->getCount() ?> reviews</span>
                </div>
                <p class="tab__text">Visually stunning, the panoramic spreads of a layflat photo book will truly memorialize your most precious moments. Developed on Fuji photo paper, these albums offer incomparable brilliance and outstanding resolution in print.</p>
                <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'layflat']) ?>" class="tab__button button">make your album</a>
                <div class="tab__check">
                    <img loading="lazy" src="/assets/images/icon-check.svg" alt="icon-check" width="24" height="24">
                    <p>Quality Guarantee included</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="1" data-name="flat-lay-photobook" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-flat-lay-photobook.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/flat-lay-photobook.jpg" alt="women viewing flat lay photobook">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">What is a Layflat Photo Book?</h2>
                <p>Layflat photo books use one single sheet of paper for each spread which is then folded down the center and glued to the next spread, creating a gorgeous collection of uninterrupted panoramic spreads.</p>
                <p>Our layflat photo albums can have up to 120 pages, which is plenty of room for all your images.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="photo-book-covers" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-photo-book-covers.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/photo-book-covers.jpg" alt="lay flat photo album book cover">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Layflat Album Covers</h2>
                <p>Offered in elegant linen, vegan leather or photo wrap, our album covers are made to encase your photos in style.</p>
                <p>All fabric covers include an embossed title in your choice of Gold, Copper, Silver, white, black or transparent. Custom embossed titles are available on request.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="layflat-photobook" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photobook.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photobook.jpg" alt="layflat book on coffee table">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Layflat Binding</h2>
                <p>Instead of digital print, which uses a series of tiny dots to print your images, PikPerfect’s layflat books are developed on archival quality Fuji Album Paper.</p>
                <p>This is a genuine silver halide paper with outstanding resolution, offering natural-looking skin tones and bold, bright colors that will last a lifetime. Select between your choice of Gloss or Pearl Matte, the latter offering a more non-reflective finish.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="layflat-photobook-box" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photobook-box.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photobook-box.jpg" alt="layflat photobook on black presentation box">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Presentation Box</h2>
                <p>Complement your layflat photobook with an elegant presentation box. Made with thick board and a black matte finish, these boxes protect your treasured photos while also offering the perfect finishing touch.</p>
            </div>
        </div>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Ready to make your Layflat Photo Book?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'layflat']) ?>" class="button button__light section-transition__button">start now</a>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-accordion">
    <div class="container">
        <h2 class="section-accordion__title">More about Lay Flat Book Printing</h2>
        <div class="accordion">
            <div class="accordion__item">
                <h3 class="accordion__title">How thick are the pages?</h3>
                <p class="accordion__text">Our layflat photo album pages are approximately 370 GSM, which is the equivalent of two photo prints stuck back-to-back with a little glue in between. If you’re looking for a thick board photo book page, choose one of our <a target="_blank" href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>">premium photo albums</a> instead.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">How many photos can I put in a layflat photo album?</h3>
                <p class="accordion__text">Our layflat albums are designed to hold a maximum of 120 pages (60 spreads) and can include up to approximately 450 photos. If you would like to show more photos, we’d recommend a <a target="_blank" href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>">custom photo book</a> instead.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">What paper choices are there?</h3>
                <p class="accordion__text">These albums are printed on Fuji Album Paper, with a choice of Pearl Matte or Gloss finish. Pearl Matte is less reflective and not as susceptible to fingerprints, while Gloss offers more intense and vivid colors.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Does the book have any branding?</h3>
                <p class="accordion__text">Our logo and a small code which is needed for production are included on the inside back cover. The logo can be removed on request.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">How long does production and shipping take?</h3>
                <p class="accordion__text">The average production time is 6-8 business days. We ship globally, so delivery times depend on the destination and mode of shipping (standard or express). You can find more details about this on the <a target="_blank" href="<?php echo $this->languageUrl('static-help-prices-') ?>">album prices</a> page.</p>
            </div>

        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>