<?php
$this->headTitle('Ein Echtfotobuch erstellen | Layflat-Fotobuch | PikPerfect');
$this->headMeta()->appendName('description', 'Ein wunderschönes Echtfotobuch oder Layflat-Fotobuch gestalten. Viele Einbandoptionen für das perfekte Fotobuch. Mit Qualitätsgarantie.');
?>
<section class="section-hero">
    <div class="container">
        <div class="section-hero__grid">
            <div class="section-hero__left">
                <div thumbsSlider="" class="swiper-container section-hero__tab-activators">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="layflat-photo-albums" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-albums.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-albums.jpg" alt="offenes Echtfotobuch Leinen Blau">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="linen-photo-album-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-linen-photo-album-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/linen-photo-album-cover.jpg" alt="Fotobuch Leineneinband mit Titelprägung">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-photo-book" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-book.jpg" alt="Paar mit Baby in offenem Echtfotobuch">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-book-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-book-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-book-cover.jpg" alt="Hochzeitspaar auf Echtfotobuch Einband">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="photo-book-presentation-box" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-photo-book-presentation-box.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/photo-book-presentation-box.jpg" alt="Echtfotobuch mit Aufbewahrungsbox">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="position: relative;">
                                <img style="width: 100%; height:auto;" src="/assets/images/hero-tab-toggle-6.jpg" alt="Flush Mount album example">
                                <img style="position: absolute; top:50% ; left:50%; transform: translate(-50%, -50%); pointer-events: none;" src="/assets/images/icons/button_play.svg">
                            </figure>
                        </div>
                    </div>
                </div>
                <div class="swiper-container section-hero__swiper">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-photo-albums" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-albums.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-albums.jpg" alt="offenes Echtfotobuch Leinen Blau">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="linen-photo-album-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-linen-photo-album-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/linen-photo-album-cover.jpg" alt="Fotobuch Leineneinband mit Titelprägung">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="layflat-photo-book" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photo-book.jpg" alt="Paar mit Baby in offenem Echtfotobuch">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="layflat-book-cover" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-book-cover.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-book-cover.jpg" alt="Hochzeitspaar auf Echtfotobuch Einband">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="photo-book-presentation-box" data-path="2.2_layflat_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-photo-book-presentation-box.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/photo-book-presentation-box.jpg" alt="Echtfotobuch mit Aufbewahrungsbox">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide hero-video-slide">
                            <div class="hero-video-slide__preloader">
                                <svg class="hero-video-slide__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
                                    <g fill="none" fill-rule="evenodd">
                                        <g transform="translate(1 1)" stroke-width="2">
                                            <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                                            <path d="M36 18c0-9.94-8.06-18-18-18">
                                                <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                                            </path>
                                        </g>
                                    </g>
                                </svg>
                            </div>

                            <div class="hero-video-slide__item"> <iframe frameborder="0" id="hero-video" src="" data-src="https://player.vimeo.com/video/569983793?background=1" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Layflat Photo Albums | PikPerfect"></iframe>
                            </div>
                        </div>

                    </div>
                    <div class="section-hero__swiper-pagination"></div>
                </div>
            </div>

            <div class="section-hero__right">
                <h1 class="tab__title">Layflat Echtfotobuch</h1>
                <p class="tab__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['layflat'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="stars tab__starts">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <span><?php echo $this->reviewsCount()->getCount() ?> Bewertungen</span>
                </div>
                <p class="tab__text">Die Panoramaseiten eines Layflat-Fotoalbums zeigen deine wertvollsten Momente auf umwerfende Weise. Entwickelt auf Fuji-Fotopapier bieten diese Alben eine hervorragende Brillanz und Auflösung deiner Foto-Erinnerungen.</p>
                <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'layflat']) ?>" class="tab__button button">ECHTFOTOBUCH MACHEN</a>
                <div class="tab__check">
                    <img loading="lazy" src="/assets/images/icon-check.svg" alt="icon-check" width="24" height="24">
                    <p>Qualitätsgarantie inklusive</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="1" data-name="flat-lay-photobook" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-flat-lay-photobook.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/flat-lay-photobook.jpg" alt="Frau schaut Echtfotobuch an">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Was ist ein Layflat-Fotobuch?</h2>
                <p>Ein Fotobuch mit Layflat-Bindung besteht aus Doppelseiten, die in der Mitte gefaltet und mit der nächsten Doppelseite verklebt werden, wodurch wunderschöne ununterbrochene Panorama-Doppelseiten entstehen.</p>
                <p>Unser Layflat-Fotoalbum hat bis zu 120 Seiten und bietet viel Platz für all deine Bilder.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="photo-book-covers" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-photo-book-covers.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/photo-book-covers.jpg" alt="Echtfotoalbum Einband">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Echtfotobuch-Einband</h2>
                <p>Deine Fotos werden stilvoll umhüllt von einem Fotobucheinband aus elegantem Leinen, veganem Leder oder Fotopapier. Alle Einbandmaterialien enthalten eine. </p>
                <p>Titelprägung in Gold, Kupfer, Silber, weiss, schwarz oder transparent. Auf Anfrage sind individuell geprägte Titel erhältlich.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="layflat-photobook" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photobook.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photobook.jpg" alt="Echtfotobuch auf Couchtisch">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Layflat-Bindung</h2>
                <p>Anstatt wie im Digitaldruck eine Reihe winziger Punkte zum Drucken der Bilder zu verwenden, werden unsere Layflat-Bücher auf Fuji-Albumpapier in Archivqualität entwickelt.</p>
                <p>Das echte Silberhalogenidpapier bietet eine hervorragende Auflösung, natürliche Hauttöne und leuchtende Farben, die ein Leben lang halten. Wähle zwischen Gloss oder Perlmutt-Finish, wobei letzterer weniger reflektiert.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="layflat-photobook-box" data-path="2.2_layflat_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.2_layflat_albums/min-layflat-photobook-box.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.2_layflat_albums/layflat-photobook-box.jpg" alt="Echtfotobuch auf schwarzer Geschenkbox">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Fotobuch-Geschenkbox</h2>
                <p>Komplettiere dein Echtfotobuch mit einer eleganten Präsentationsbox. Die Geschenkschachteln aus dickem Karton und mattschwarzer Oberfläche schützen und bieten gleichzeitig den perfekten letzten Schliff.</p>
            </div>
        </div>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Bereit, dein Echtfotobuch zu erstellen?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'layflat']) ?>" class="button button__light section-transition__button">JETZT STARTEN</a>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-accordion">
    <div class="container">
        <h2 class="section-accordion__title">Mehr über Layflat-Fotobücher</h2>
        <div class="accordion">
            <div class="accordion__item">
                <h3 class="accordion__title">Wie dick sind die Seiten?</h3>
                <p class="accordion__text">Unsere Echtfotobuchseiten sind ungefähr 370 g/m2 schwer, was zwei Fotoabzügen entspricht, die mit etwas Klebstoff gegeneinander geklebt werden. Wenn du extradicke Fotobuchseiten suchst, wähle stattdessen unserer <a target="_blank" href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>">Premium-Fotoalbum.</a></p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Wie viele Fotos kann ich in einem Layflat-Fotoalbum unterbringen?</h3>
                <p class="accordion__text">Unser Layflat-Album ist für maximal 120 Seiten (60 Doppelseiten) ausgelegt und kann bis zu ca. 450 Fotos enthalten. Bei mehr Fotos empfehlen wir stattdessen ein <a target="_blank" href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>">Hardcover Fotobuch.</a>  </p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Welche Papierauswahl gibt es?</h3>
                <p class="accordion__text">Diese Alben werden auf Fuji-Albumpapier gedruckt, wahlweise mit Perlmutt- oder Gloss-Finish. Perlmutt ist weniger reflektierend, während Gloss etwas lebendigere Farben bietet.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Hat das Buch ein Firmenlogo?</h3>
                <p class="accordion__text">Unser Logo und ein kleiner Code, der für die Produktion benötigt wird, befinden sich auf der hinteren Umschlaginnenseite. Das Logo kann auf Wunsch entfernt werden. </p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Wie lange dauern Produktion und Versand?</h3>
                <p class="accordion__text">Die durchschnittliche Produktionszeit beträgt 6-8 Werktage. Wir versenden weltweit, daher hängt die Lieferzeiten vom Zielort und der Versandart (Standard oder Express) ab. Weitere Informationen dazu sind auf der Seite <a target="_blank" href="<?php echo $this->languageUrl('static-help-prices-') ?>">Fotobuchpreise </a> zu finden</p>
            </div>

        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>