<?php
$this->headTitle('Make your own Cookbook | DIY Recipe Books | PikPerfect');
$this->headMeta()->appendName('description', 'Make a custom recipe cookbook to make sure your family\'s favourites are passed on to the generations to come.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero__image-left">
  <div class="section-hero__wrap-flex">
    <div class="section-hero__image-col px-0">
      <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
        <picture data-priority="0" data-name="custom-cookbook" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
          <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-custom-cookbook.webp" type="image/webp">
          <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/custom-cookbook.jpg" alt="Custom cookbook standing on kitchen counter with dumpling recipe">
        </picture>

      </figure>


    </div>
    <div class="section-hero__content-col section-hero__content-col_orange">
      <div class="section-hero__bg">
        <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
          <source class="toggle-img--js" srcset="/assets/images/towebp/min-image_texture.webp" type="image/webp">
          <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/image_texture.jpg" alt="bg-hero">
        </picture>


      </div>
      <h1 class="section-hero__size-title">Custom Cookbooks</h1>
      <p>Connect with generations past and future with a custom family recipe book.</p>
      <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=5" class="button button__orange">start now</a>
      <p class="price"><?php echo $this->translate('From') . ' ' . $this->format(
                          $this->smallestPrices['photobook'],
                          $region->iso,
                          2,
                          $region->symbol
                        ); ?></p>
    </div>
  </div>
</section>
<section class="section-text section-text_padding">
  <div class="section-text__container">
    <div class="section-text__content">
      <p>Good food tends to bring us together, whether it's cooking with friends, experimenting with the kids, or just indulging in our favorite dishes. Making a personalized Cookbook ensures your family recipes are not forgotten, and are passed on to the generations to come.</p>
    </div>
  </div>
</section>
<section class="section-service section-service_big-cards">
  <div class="section-service__cards">
    <div class="section-service__card">
      <h3 class="section-service__number">1.</h3>
      <h4 class="section-service__name-service">You Choose</h4>
      <p>Select your preferred photobook type and album design style, upload your photos.</p>
    </div>
    <div class="section-service__card">
      <h3 class="section-service__number">2.</h3>
      <h4 class="section-service__name-service">We Design</h4>
      <p>Our expert photo book designers bring your album to life. Includes unlimited free revisions.</p>
    </div>
    <div class="section-service__card">
      <h3 class="section-service__number">3.</h3>
      <h4 class="section-service__name-service">Pay to Print</h4>
      <p>Only pay when you’re 100% <br> satisfied with the design <br> (no commitment to purchase).</p>
    </div>
  </div>
</section>
<section class="section-img section-img_size-m">
  <div class="section-img__container">
    <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
      <picture data-priority="2" data-name="recipe-photo-book" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
        <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-recipe-photo-book.webp" type="image/webp">
        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/recipe-photo-book.jpg" alt="Personalized recipe photo book with clam chowder recipe">
      </picture>

    </figure>


  </div>
</section>
<section class="section-img-text">
  <div class="section-img-text__container">
    <div class="section-img-text__wrap">
      <div class="section-img-text__img">
        <figure>
          <picture data-priority="1" data-name="placeholder2" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-placeholder2.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/placeholder2.jpg" alt="close cookbook munchimg in munchen">
          </picture>


        </figure>
      </div>
      <div class="section-img-text__content">
        <div class="section-img-text__content-wrap">
          <h2 class="section-img-text__title">DIY Cookbook Ideas</h2>
          <p>A personalized family recipe book is a photo book filled with grandma's favorite recipes, capturing not only notes and photos of the food, but the memories that come along with them. PikPerfect’s recipe photo books are easy to make, fun to read, and make the perfect gift for family and close friends.</p>
        </div>
      </div>
    </div>
    <div class="section-img-text__wrap section-img-text__wrap_order">
      <div class="section-img-text__img">
        <figure>
          <picture data-priority="1" data-name="placeholder3" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-placeholder3.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/placeholder3.jpg" alt="open cookbook on page chana masala">
          </picture>


        </figure>
      </div>
      <div class="section-img-text__content">
        <div class="section-img-text__content-wrap">
          <p>You can choose from a range of different album covers and paper types to create your own recipe book. Our <a target="_blank" class="link" href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>">custom photo book</a> are the most popular option as these can have up to 240 digitally printed pages, and are book-bound to make for a lasting keepsake. If you’re looking for something higher-end, a <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" target="_blank" class="link">layflat album</a> would be another option, but please keep in mind that these pages are developed on Fuji photo paper, so like any photo print, will be a little sensitive to moisture.</p>
          <div class="section-img-text__button">
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=5" class="button ">start now</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-album section-album_size-lx">
  <div class="section-album__container">
    <div class="section-album__wrap-content">
      <h2 class="section-album__title">Cookbook Design Styles</h2>
      <p class="section-album__entered">Designing your DIY recipe book involves a lot more than just throwing some photos and text on to a page. Our experienced photo book designers will help bring this to life: send us your photos and recipes along with an idea of what you’re looking for, we’ll then offer you a number of different options and allow you to pick the one/s you like best. All designs include unlimited free revisions, making sure your cookbook photo book or personalized baking recipe book is perfect before it’s sent to print.</p>
    </div>
    <div class="swiper-container swiperalbum ">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="1" data-name="image_cookbook_example_1" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_1.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_1.jpg" alt="album A Man, A Pan & A Plan light yellow">
            </picture>

          </figure>


          <h3 class="section-album__name-title">The Chopra Cookbook<span>Cookbook</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_cookbook_example_2" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_2.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_2.jpg" alt="album A Man, A Pan & A Plan gray">
            </picture>

          </figure>


          <h3 class="section-album__name-title">The Family Cookbook<span>Cookbook</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_cookbook_example_3" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_3.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_3.jpg" alt="album A Man, A Pan & A Plan light brown">
            </picture>

          </figure>


          <h3 class="section-album__name-title">A Man, A Pan & A Plan<span>Cookbook</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_cookbook_example_4" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_4.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_4.jpg" alt="album A Man, A Pan & A Plan light yellow">
            </picture>

          </figure>


          <h3 class="section-album__name-title">A Man & A Pan<span>Cookbook</span></h3>
        </div>
      </div>
      <div class="swiper-pagination swiperalbum-pagination"></div>
    </div>
    <div class="section-album__button">
      <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
    </div>
  </div>
</section>
<section class="section-reviews">
  <div class="container">
    <h2 class="d-none"> reviews</h2>
    <?php echo $this->partial('application/partial/reviews') ?>
    <?php echo $this->partial('application/partial/reviews-box') ?>
  </div>
</section>
<section class="section-transition">
  <div class="container">
    <div class="section-transition__content">
      <h2 class="section-transition__title">Ready to make a personalized Cookbook?</h2>
    </div>
    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=5" class="button button__light section-transition__button section-transition__button_big">start now</a>
  </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
  <div class="section-text__container">
    <h2 class="section-text__title">Making a Cookbook Online</h2>
    <div class="section-text__content">
      <p>Making your own recipe book makes for the ideal gift! Print one for yourself and make duplicate copies to give to family and friends, and connect with them in their own kitchens.</p>
      <p>Preparing to make your own cookbook and then bringing it to life in a beautifully designed and <a href="<?php echo $this->languageUrl('static-photo-books-') ?>" target="_blank" class="link">printed photo book</a> used to be an intimidating task, but no longer. PikPerfect's team of experienced book designers are here to help: all you need to do is curate a list of the recipes you would like to include, and ideally, some photos of the finished product, and send those in to us. We’ll then sort through and lay these out for you in a beautifully crafted recipe book, giving you different styles and designs to choose from. The end result will be a proud centerpiece of any kitchen table.</p>
    </div>
  </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>