<?php
$this->headTitle('Fotobuch Kochbuch erstellen | Rezeptfotobuch | PikPerfect');
$this->headMeta()->appendName('description', 'Ein Kochbuch oder Backbuch gestalten einfach gemacht: Unser Designteam erstellt ein Familien Rezeptbuch genau nach deinen Wünschen. Mit Qualitätsgarantie.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero__image-left">
  <div class="section-hero__wrap-flex">
    <div class="section-hero__image-col px-0">
      <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
        <picture data-priority="0" data-name="custom-cookbook" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
          <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-custom-cookbook.webp" type="image/webp">
          <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/custom-cookbook.jpg" alt="Individuell gestaltetes Kochbuch auf Küchenzeile mit Teigtaschen Rezept">
        </picture>

      </figure>


    </div>
    <div class="section-hero__content-col section-hero__content-col_orange">
      <div class="section-hero__bg">
        <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
          <source class="toggle-img--js" srcset="/assets/images/towebp/min-image_texture.webp" type="image/webp">
          <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/image_texture.jpg" alt="bg-hero">
        </picture>


      </div>
      <h1 class="section-hero__size-title">Kochbuch Fotobuch</h1>
      <p>Ein Rezeptbuch selber machen verbindet über Generationen.</p>
      <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=5" class="button button__orange">JETZT ANFANGEN</a>
      <p class="price"><?php echo $this->translate('Ab') . ' ' . $this->format(
                          $this->smallestPrices['photobook'],
                          $region->iso,
                          2,
                          $region->symbol
                        ); ?></p>
    </div>
  </div>
</section>
<section class="section-text section-text_padding">
  <div class="section-text__container">
    <div class="section-text__content">
      <p>Gutes Essen bringt uns zusammen, sei es beim Kochen mit Freunden, beim Experimentieren mit den Kindern oder einfach nur beim Geniessen der Lieblingsgerichte. Durch die Erstellung eines Kochbuch als Fotobuch gehen deine Familienrezepte nicht vergessen und werden an kommende Generationen weitergegeben.</p>
    </div>
  </div>
</section>
<section class="section-service section-service_big-cards">
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">Du wählst</h4>
            <p>Teil uns deinen gewünschten Fotobuchtyp und Albumdesignstil mit und lade deine Fotos hoch.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">Wir gestalten</h4>
            <p>Unsere Fotobuchdesigner erwecken dein Album zum Leben. Überarbeitungen inklusive.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Zahle zum Drucken</h4>
            <p>Zahle erst, wenn du 100 % mit dem Design zufrieden bist <br>(ohne Kaufverpflichtung).</p>
        </div>
    </div>
</section>
<section class="section-img section-img_size-m">
  <div class="section-img__container">
    <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
      <picture data-priority="2" data-name="recipe-photo-book" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
        <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-recipe-photo-book.webp" type="image/webp">
        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/recipe-photo-book.jpg" alt="Individuell gestaltetes Rezeptfotobuch mit Rezept für Muschelsuppe">
      </picture>

    </figure>


  </div>
</section>
<section class="section-img-text">
  <div class="section-img-text__container">
    <div class="section-img-text__wrap">
      <div class="section-img-text__img">
        <figure>
          <picture data-priority="1" data-name="placeholder2" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-placeholder2.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/placeholder2.jpg" alt="close cookbook munchimg in munchen">
          </picture>


        </figure>
      </div>
      <div class="section-img-text__content">
        <div class="section-img-text__content-wrap">
          <h2 class="section-img-text__title">DIY Kochbuch Ideen</h2>
          <p>Ein personalisiertes Familien Rezeptbuch ist ein Fotobuch, das mit Lieblingsrezepten gefüllt ist und nicht nur Notizen und Fotos des Essens, sondern auch die damit verbundenen Erinnerungen festhält. Ein Fotobuch mit Rezepten ist mit PikPerfect ganz einfach zu erstellen und das perfekte Geschenk für Familie und enge Freunde.</p>
        </div>
      </div>
    </div>
    <div class="section-img-text__wrap section-img-text__wrap_order">
      <div class="section-img-text__img">
        <figure>
          <picture data-priority="1" data-name="placeholder3" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-placeholder3.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/placeholder3.jpg" alt="open cookbook on page chana masala">
          </picture>


        </figure>
      </div>
      <div class="section-img-text__content">
        <div class="section-img-text__content-wrap">
          <p>Wähle aus verschiedenen Fotobucheinbänden und Papiersorten für dein eigenes Koch- oder Backbuch. Unser <a target="_blank" class="link" href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>">Hardcover Fotobuch</a> ist am beliebtesten, da es bis zu 240 digital gedruckte Seiten umfassen kann und für eine bleibende Erinnerung in PUR-Klebebindung gebunden ist. Für ein hochwertigeres Kochbuch ist unser <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" target="_blank" class="link">Echtfotobuch</a> eine weitere Option, wobei dessen Seiten auf Fuji-Fotopapier entwickelt werden und daher ein wenig feuchtigkeitsempfindlich sind.</p>
          <div class="section-img-text__button">
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=5" class="button ">JETZT STARTEN</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-album section-album_size-lx">
  <div class="section-album__container">
    <div class="section-album__wrap-content">
      <h2 class="section-album__title">Kochbuch gestalten Beispiele</h2>
      <p class="section-album__entered">Ein Rezeptbuch selbst zu gestalten umfasst viel mehr, als ein paar Fotos und Text auf eine Seite zu werfen. Unsere erfahrenen Fotobuch Designer helfen dir dabei, es mit Leben zu füllen: Schick uns deine Fotos und Rezepte zusammen mit einer Vorstellung für dein persönliches Rezeptbuch, und wir zeigen dir verschiedene Vorlagen zur Auswahl. Unbegrenzte Überarbeitungen inklusive, damit dein Kochbuch-Fotobuch oder personalisiertes Backrezeptbuch perfekt ist, bevor es in Druck geht.</p>
    </div>
    <div class="swiper-container swiperalbum ">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="1" data-name="image_cookbook_example_1" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_1.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_1.jpg" alt="album A Man, A Pan & A Plan light yellow">
            </picture>

          </figure>


          <h3 class="section-album__name-title">The Chopra Cookbook<span>Cookbook</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_cookbook_example_2" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_2.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_2.jpg" alt="album A Man, A Pan & A Plan gray">
            </picture>

          </figure>


          <h3 class="section-album__name-title">The Family Cookbook<span>Cookbook</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_cookbook_example_3" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_3.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_3.jpg" alt="album A Man, A Pan & A Plan light brown">
            </picture>

          </figure>


          <h3 class="section-album__name-title">A Man, A Pan & A Plan<span>Cookbook</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_cookbook_example_4" data-path="2.7-cookbook-recipe-photobooks" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.7-cookbook-recipe-photobooks/min-image_cookbook_example_4.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.7-cookbook-recipe-photobooks/image_cookbook_example_4.jpg" alt="album A Man, A Pan & A Plan light yellow">
            </picture>

          </figure>


          <h3 class="section-album__name-title">A Man & A Pan<span>Cookbook</span></h3>
        </div>
      </div>
      <div class="swiper-pagination swiperalbum-pagination"></div>
    </div>
    <div class="section-album__button">
      <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
    </div>
  </div>
</section>
<section class="section-reviews">
  <div class="container">
    <h2 class="d-none"> reviews</h2>
    <?php echo $this->partial('application/partial/reviews') ?>
    <?php echo $this->partial('application/partial/reviews-box') ?>
  </div>
</section>
<section class="section-transition">
  <div class="container">
    <div class="section-transition__content">
      <h2 class="section-transition__title">Bereit, ein Kochbuch selbst zu gestalten?</h2>
    </div>
    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=5" class="button button__light section-transition__button section-transition__button_big">JETZT LOSLEGEN</a>
  </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
  <div class="section-text__container">
    <h2 class="section-text__title">Ein Kochbuch online erstellen</h2>
    <div class="section-text__content">
      <p>Ein eigenes Kochbuch drucken lassen ist das ideale Geschenk! Erstell eines für dich selbst und weitere Exemplare zum Verschenken an Familie und Freunde.</p>
      <p>Ein eigenes Rezeptbuch erstellen und es in einem wunderschön gestalteten und  <a href="<?php echo $this->languageUrl('static-photo-books-') ?>" target="_blank" class="link">gedruckten Fotobuch</a> zum Leben zu erwecken muss kein grosses Unterfangen sein. Das PikPerfect-Team erfahrener Fotobuchdesigner hilft dir: Du erstellst lediglich die Liste der Rezepte und schickst sie uns zusammen mit einigen Fotos der fertigen Gerichte. Wir geben dir verschiedene Stile und Vorlagen zur Auswahl und stellen alles in einem wunderschön gestalteten Rezeptbuch zusammen. Das Endergebnis wird ein stolzer Mittelpunkt jedes Küchentisches sein.</p>
    </div>
  </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>