<?php
$this->headTitle('Parent Wedding Albums & Photo Books | PikPerfect');
$this->headMeta()->appendName('description', 'Parent albums are smaller duplicates of your main photo album and make the ideal “Thank You” for all the love and support your family has provided.');
$region = $this->region()->getUserRegion();
?>

<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="parent-wedding-albums" data-path="16.1" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/16.1/min-parent-wedding-albums.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.1/parent-wedding-albums.jpg" alt="Parent wedding album copies laying on wooden table">
                </picture>
            </figure>
        </div>
        <div class="section-hero__content-col section-hero__content-col_light-brown">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Parent Albums</h1>
            <p style="font-size: 16px;">Parent albums are smaller duplicates of your main photo album and make the ideal “Thank You” for all the love and support your family has provided.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-') ?>" class="button button__light-brown">start now</a>
        </div>
    </div>
</section>
<section class="img-half-text">
    <div class="img-half-text__container">
        <div class="img-half-text__wrap">
            <div class="img-half-text__img">
                <figure style="padding-bottom: calc(500% / 620 * 100)" class="figure-webp">
                    <picture data-priority="0" data-name="parent-albums" data-path="16.1" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/16.1/min-parent-albums.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.1/parent-albums.jpg" alt="Parent photo album wrapped as a gift">
                    </picture>

                </figure>


            </div>
            <div class="img-half-text__context">
                <h2 class="title">Parent Wedding Albums</h2>
                <div class="img-half-text__list">
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>personalize cover images or title</p>
                    </div>
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>add text inside the albums, such as personal thank you notes</p>
                    </div>
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>swap out individual images</p>
                    </div>
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>add/remove pages from design</p>
                    </div>
                </div>
                <p>Your personal designer will be happy to help with any other requests you may have.</p>
            </div>
        </div>
    </div>
</section>

<section class="section-accordion section-accordion_light section-accordion_m-size">
    <div class="container">
        <h2 class="section-accordion__title title-with-text">More about our Wedding Albums for Parents</h2>
        <p class="text-entered">We get a lot of questions about our wedding photo books for parents as they are a popular option with most couples, so we’ve put together some answers to the most common questions.</p>
        <div class="accordion">
            <div class="accordion__item">
                <h3 class="accordion__title">How much do parent albums cost?</h3>
                <p class="accordion__text">As parent album copies are generally smaller and/or printed on thinner paper, they cost considerably less than your main album. When the album design has been approved, you’ll find all available parent album copy options in your shopping cart along with the associated cost. The choices and corresponding cost depend on the type and size of the main album, but if you’re looking for something different, reach out to your designer and they’ll be happy to help customize your order to meet your requirements.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">What album sizes are available?</h3>
                <p class="accordion__text">Standard parent album formats are smaller than your main album. For example, if your main album is 16x12 inches, when you approve the design you’ll see the option to add parent copies in 12x8 and 8x6 inches. That said, you can opt to have the parent albums in the same size as the main album, but change the paper or number of pages.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Do they have exactly the same design as the main album?</h3>
                <p class="accordion__text">By default, yes: parent wedding book copies will have exactly the same design and number of pages as the main album. If you’d like to reduce the number of pages, or customize a few pages or cover to focus on the bride’s and groom’s parents, or other family members, our album design team will be happy to help do this.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">What cover will my parents photo albums have?</h3>
                <p class="accordion__text">To help keep the cost of parent photo album copies down, they will always default to a printed photo cover. If you’d prefer to have exactly the same cover as the main album, or customize the cover for a particular family member, our design team will be happy to update this for you.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">What paper options are available?</h3>
                <p class="accordion__text">To help minimize the cost of parent albums, we print these with a thinner paper, when available. If you’re ordering a <a href="https://www.pikperfect.com/photo-books/premium-layflat-albums" target="_blank" class="link">premium photo album with thick pages</a>, the parent copies for these will have the same paper quality, but the paper will be thinner (no cardboard inserts). Smaller duplicates of our <a href="https://www.pikperfect.com/photo-books/layflat-photo-albums" target="_blank" class="link">layflat albums and books</a> have the same paper as the main album. Photo book parent copies are always printed on 170 GSM matte paper.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Do they need to be ordered together with the main album?</h3>
                <p class="accordion__text">We recommend ordering your parent photobook copies along with the main album as you’ll save on shipping since we charge a flat rate shipping per order. But we do store the print files for 6 months from date of purchase, so you’re also welcome to order them at a later time.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Can I add a box for my parent albums?</h3>
                <p class="accordion__text">Please let your designer know if you’d like to add a <a href="https://www.pikperfect.com/photo-books/photo-album-boxes" target="_blank" class="link">photo book presentation box</a> with your parent copies. These are available with all album and photo book sizes except for the pocket books (6x6 and 8x6 inches).</p>
            </div>

        </div>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us', ['color' => 'dignity_gray']) ?>



<?php echo $this->render('partial/quick_chat.phtml'); ?>