<?php
$this->headTitle('Hochzeitsalbum Fotobuch Kopien für Eltern | PikPerfect');
$this->headMeta()->appendName('description', 'Elternkopien sind kleinere Exemplare des Hauptfotoalbums und das ideale „Dankeschön“ oder Geschenk für Familie und Freunde.');
$region = $this->region()->getUserRegion();
?>

<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="parent-wedding-albums" data-path="16.1" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/16.1/min-parent-wedding-albums.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.1/parent-wedding-albums.jpg" alt="Elternkopien Hochzeitsalbum auf Holztisch">
                </picture>
            </figure>
        </div>
        <div class="section-hero__content-col section-hero__content-col_light-brown">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Elternkopien</h1>
            <p style="font-size: 16px;">Elternexemplare sind kleinere Kopien deines Hauptalbums und das ideale Dankeschön für die Liebe und Unterstützung deiner Familie.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-') ?>" class="button button__light-brown">BUCH STARTEN</a>
        </div>
    </div>
</section>
<section class="img-half-text">
    <div class="img-half-text__container">
        <div class="img-half-text__wrap">
            <div class="img-half-text__img">
                <figure style="padding-bottom: calc(500% / 620 * 100)" class="figure-webp">
                    <picture data-priority="0" data-name="parent-albums" data-path="16.1" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/16.1/min-parent-albums.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/16.1/parent-albums.jpg" alt="Eltern Fotoalbum als Geschenk verpackt">
                    </picture>

                </figure>


            </div>
            <div class="img-half-text__context">
                <h2 class="title">Hochzeitsalbum für Eltern</h2>
                <div class="img-half-text__list">
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>Titelbild oder Titel anpassen</p>
                    </div>
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>Text innen hinzufügen, z.B. Sprüche oder Danksagungen</p>
                    </div>
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>einzelne Bilder austauschen</p>
                    </div>
                    <div class="img-half-text__list-item">
                        <img src="/assets/images/ic_circle_check.svg" alt="ic_circle_check">
                        <p>Hinzufügen/Entfernen von Seiten</p>
                    </div>
                </div>
                <p>Dein persönlicher Designer hilft dir gerne bei allen anderen Wünschen.</p>
            </div>
        </div>
    </div>
</section>

<section class="section-accordion section-accordion_light section-accordion_m-size">
    <div class="container">
        <h2 class="section-accordion__title title-with-text">Mehr über Fotobuch Kopien für Eltern</h2>
        <p class="text-entered">Hochzeitsfotobücher für Eltern sind bei den meisten Paaren sehr beliebt. Deshalb haben wir hier einige Antworten auf die häufigsten Fragen zusammengestellt. </p>
        <div class="accordion">
            <div class="accordion__item">
                <h3 class="accordion__title">Wie viel kosten Exemplare für Familie & Freunde?</h3>
                <p class="accordion__text">Da Elternkopien in der Regel kleiner sind und/oder auf dünnerem Papier gedruckt werden, kosten sie deutlich weniger als das Hauptalbum. Nach der Freigabe des Designs deines Albums findest du im Warenkorb alle Optionen für Elternalben sowie die entsprechenden Kosten. Die Auswahl hängt von der Art und Grösse des Hauptalbums ab. Wende dich an deinen Designer, falls du Fragen hast, Hilfe brauchst oder Anpassungen machen möchtest.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Welche Albumgrössen sind verfügbar?</h3>
                <p class="accordion__text">Normalerweise sind Elternkopien eins kleiner als das Hauptalbum: Hat das Hauptalbum das Format A3, siehst du nach Freigabe des Designs Elternexemplare in A4 und A5. Natürlich kannst du auch einfach weitere Exemplare des Hauptalbums bestellen, wobei sich das Papier oder die Anzahl der Seiten anpassen lässt (frag deinen Designer hierzu).</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Ist das Design gleich wie beim Hauptalbum?</h3>
                <p class="accordion__text">Standardmässig ja: Die Kopien eines Hochzeitsfotobuchs haben genau das gleiche Design und die gleiche Seitenzahl wie das Hauptalbum. Unser Designteam hilft dir gerne, einige Seiten oder den Einband anzupassen, um die Eltern des Paars oder andere Familienmitglieder in den Mittelpunkt zu stellen.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Welchen Einband haben meine Eltern-Fotoalben?</h3>
                <p class="accordion__text">Um die Kosten für die Elternkopien niedrig zu halten, haben sie immer einen gedruckten Fotoeinband. Wenn du den gleichen Einband wie beim Hauptalbum wünschst oder den Einband für ein bestimmtes Familienmitglied anpassen möchtest, ändert das unser Designteam gerne für dich.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Welche Papiere sind verfügbar?</h3>
                <p class="accordion__text">Um die Kosten für Elternalben zu minimieren, drucken wir sie mit dünnerem Papier, wenn möglich. Bei Bestellung eines <a href="https://www.pikperfect.com/photo-books/premium-layflat-albums" target="_blank" class="link">Premium Layflat-Albums mit dicken Seiten</a>haben die Elternkopien das gleiche Papier, nur ohne Kartoneinlagen. Kleinere Kopien unserer <a href="https://www.pikperfect.com/photo-books/layflat-photo-albums" target="_blank" class="link">Layflat-Echtfotobücher </a> haben das gleiche Papier wie das Hauptalbum. Fotobuch-Elternkopien werden immer auf 170g-Papier gedruckt.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Müssen sie zusammen mit dem Hauptalbum bestellt werden?</h3>
                <p class="accordion__text">Wenn du die Fotobuch Elternkopien zusammen mit dem Hauptalbum bestellst, sparst du wegen des Versandfestpreises. Wir bewahren die Druckdateien aber auch 6 Monate ab Kaufdatum auf, so dass du sie gerne zu einem späteren Zeitpunkt bestellen kannst.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Gibt es eine Geschenkbox für Elternkopien?</h3>
                <p class="accordion__text">Bitte teil deinem Designer mit, falls du eine <a href="https://www.pikperfect.com/photo-books/photo-album-boxes" target="_blank" class="link">Fotobuch-Schachtel</a>  für ​​deine Elternalben möchtest. Sie sind für alle Formate grösser als Pocket (A5) erhältlich.</p>
            </div>

        </div>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us', ['color' => 'dignity_gray']) ?>



<?php echo $this->render('partial/quick_chat.phtml'); ?>