<?php
$this->headTitle('Ein Babyfotoalbum & Babyfotobuch erstellen | PikPerfect');
$this->headMeta()->appendName('description', 'Ein Babyfotobuch gestalten war noch nie so einfach: Unsere Designer erstellen ein wertvolles Baby-Fotoalbum für dich. Mit Qualitätsgarantie.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero__image-left">
  <div class="section-hero__wrap-flex">
    <div class="section-hero__image-col px-0">
      <figure class="figure-webp">
        <picture data-priority="0" data-name="baby-photo-books" data-path="2.6_baby_photo_books" class="picture-webp">
          <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-baby-photo-books.webp" type="image/webp">
          <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/baby-photo-books.jpg" alt="Hochwertiges Baby Fotoabuch mit dicken Echtfoto Seiten">
        </picture>


      </figure>
    </div>
    <div class="section-hero__content-col section-hero__content-col_blue">
      <div class="section-hero__bg">
        <picture data-priority="0" data-name="image_texture" data-path=" class=" picture-webp">
          <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
          <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
        </picture>


      </div>
      <div class="section-hero__picture section-hero__picture_baby">
        <picture>
          <source media="(max-width: 500px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">
          <img src="/assets/images/towebp/2.6_baby_photo_books/illustration_hero_baby_photo_books.png" alt="picture hero fox">
        </picture>
      </div>
      <h1 class="section-hero__size-title">Baby Fotobuch</h1>
      <p style="max-width: 330px;" class="m-auto">Erstelle mit Hilfe unserer Designspezialisten ein wundervolles Baby Fotoalbum.</p>
      <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=2" class="button button__blue-opacity">start now</a>
      <p class="small">No advance payment required</p>
    </div>
  </div>
</section>
<section class="dignity dignity_blocks">
    <div class="dignity__container">
        <div class="dignity__wrap">
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_the_human_touch.svg" alt="circle_the_human_touch">
                </div>
                <div class="dignity__content">
                    <h3>Die persönliche Note</h3>
                    <p> Wir helfen die besten Fotos auswählen und gestalten das Album mit dir.</p>
                </div>
            </div>
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_attention_to_detail.svg" alt="circle_attention_to_detail">
                </div>
                <div class="dignity__content">
                    <h3>Liebe zum Detail</h3>
                    <p>Jedes Fotobuch wird vor dem Druck geprüft und danach sorgfältig verpackt.</p>
                </div>
            </div>
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_premium_materials.svg" alt="circle_premium_materials">
                </div>
                <div class="dignity__content">
                    <h3>Premium Materialien</h3>
                    <p>Gefertigt mit den hochwertigsten Einbänden und Papieren.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
  <div class="description-img__container">
    <div class="description-img__wrap">
      <div class="description-img__img">
        <div class="swiper-container swiperDescription">
          <div class="swiper-wrapper">
            <div class="swiper-slide">
              <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                <picture data-priority="1" data-name="baby-photo-album-book" data-path="2.6_baby_photo_books" class="picture-webp">
                  <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-baby-photo-album-book.webp" type="image/webp">
                  <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/baby-photo-album-book.jpg" alt="Frau schaut sich Baby Fotobuch auf Teppich an">
                </picture>

              </figure>

            </div>
            <div class="swiper-slide">
              <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                <picture data-priority="2" data-name="photo-book" data-path="2.6_baby_photo_books" class="picture-webp">
                  <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-photo-book.webp" type="image/webp">
                  <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/photo-book.jpg" alt="Offenes Fotobuch">
                </picture>

              </figure>

            </div>
          </div>
          <div class="swiperDescription-pagination"></div>
        </div>
      </div>
      <div class="description-img__content description-img__content_padding">
        <h2 class="description-img__title"><span>Unser Klassiker</span>Babyfotobuch</h2>
        <p>Digital gedruckt auf hochwertigem Fotopapier können diese grossen Baby-Fotobücher mit bis zu 244 Seiten bis zu 1.000 Fotos zeigen.</p>
        <p>Ideal für Eltern, die jeden wertvollen Moment im ersten Lebensjahr ihres Kindes festhalten wollen. Baby-Fotoalben von PikPerfect sind ein Herzstück auf jedem Kaffeetisch.</p>
        <p class="description-img__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['photobook'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                          ); ?>.</p>
        <div class="description-img__buttons">
          <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=2" class="button">BESTELLEN </a>
          <a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" class="button button__gray">   MEHR ERFAHREN
</a>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="description-img description-img__order">
  <div class="description-img__container">
    <div class="description-img__wrap">
      <div class="description-img__img">
        <div class="swiper-container swiperDescription">
          <div class="swiper-wrapper">
            <div class="swiper-slide">
              <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                <picture data-priority="1" data-name="baby-photo-album" data-path="2.6_baby_photo_books" class="picture-webp">
                  <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-baby-photo-album.webp" type="image/webp">
                  <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/baby-photo-album.jpg" alt="Baby Fotoalbum auf Couchtisch">
                </picture>

              </figure>

            </div>
            <div class="swiper-slide">
              <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                <picture data-priority="2" data-name="layflat-baby-book" data-path="2.6_baby_photo_books" class="picture-webp">
                  <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-layflat-baby-book.webp" type="image/webp">
                  <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/layflat-baby-book.jpg" alt="Baby Echtfotobuch Bindung Details">
                </picture>

              </figure>

            </div>
          </div>
          <div class="swiperDescription-pagination"></div>
        </div>
      </div>
      <div class="description-img__content description-img__content_padding">
        <h2 class="description-img__title"><span>Unser Bestseller</span>Layflat <br> Babyfotoalbum </h2>
        <p>Unser Baby Fotoalbum mit einem fast unsichtbaren Falz: Da sie flach aufliegen, werden deine Lieblingsbilder auf wunderschönen Panorama-Doppelseiten präsentiert. </p>
        <p>Das Layflat Baby Fotobuch ist eine beliebte Wahl bei vielen frischgebackenen Eltern und wird auf echtem Fuji-Fotopapier mit perlmatter oder glänzender Oberfläche entwickelt.</p>
        <p class="description-img__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['layflat'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                          ); ?>.</p>
        <div class="description-img__buttons">
          <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'layflat']) ?>?occasion=2" class="button">BESTELLEN </a>
          <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" class="button button__gray">MEHR ERFAHREN
</a>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="description-img">
  <div class="description-img__container">
    <div class="description-img__wrap">
      <div class="description-img__img">
        <div class="swiper-container swiperDescription">
          <div class="swiper-wrapper">
            <div class="swiper-slide">
              <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                <picture data-priority="1" data-name="baby-boy-photo-book" data-path="2.6_baby_photo_books" class="picture-webp">
                  <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-baby-boy-photo-book.webp" type="image/webp">
                  <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/baby-boy-photo-book.jpg" alt="Baby Fotobuch mit Junge">
                </picture>

              </figure>

            </div>
            <div class="swiper-slide">
              <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                <picture data-priority="2" data-name="premium-photo-album" data-path="2.6_baby_photo_books" class="picture-webp">
                  <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-premium-photo-album.webp" type="image/webp">
                  <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/premium-photo-album.jpg" alt="Hochwertiges Premium Fotoalbum mit extra dicken Layflat Seiten">
                </picture>

              </figure>

            </div>
          </div>
          <div class="swiperDescription-pagination"></div>
        </div>
      </div>
      <div class="description-img__content description-img__content_padding">
        <h2 class="description-img__title"><span>Unsere Luxuslinie</span> Premium Layflat Babyalbum</h2>
        <p>Eines der besten Baby-Fotoalben auf dem Markt: Handgefertigt für ein massgeschneidertes Finish mit dicken Echtfoto-Seiten und einem Einband deiner Wahl aus echtem Leder, elegantem Leinen oder edel bedrucktem Cover.</p>
        <p> Auf Fotopapier in Archivqualität gefertigt verwandeln sie Babies erstes Fotoalbum in wahrhaft bleibende Erinnerungen.</p>
        <p class="description-img__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['premium'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                          ); ?>.</p>
        <div class="description-img__buttons">
          <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'premium']) ?>?occasion=2" class="button">BESTELLEN </a>
          <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" class="button button__gray">MEHR ERFAHREN
</a>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-img">
  <figure style="padding-bottom: calc(724% / 1440 * 100)" class="figure-webp">
    <picture data-priority="2" data-name="baby-album-designs" data-path="2.6_baby_photo_books" class="picture-webp">
      <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-baby-album-designs.webp" type="image/webp">
      <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/baby-album-designs.jpg" alt="Gestaltung Beispiele Baby Fotobuch">
    </picture>

  </figure>


</section>
<section class="section-service">
  <h2 class="section-service__title">Babyfotobuch gestalten – erledigt!</h2>
  <p class="section-service__entered">Mit einem Neugeborenen hat man alle Hände voll zu tun. Mach dir das Leben leichter und arbeite mit einem unserer Designer zusammen, um ein Fotobuch von Babys erstem Jahr zu gestalten. Wir helfen beim Sortieren Tausender Fotos und gestalten das Album nach deinen Vorstellungen. Mit unbegrenzten kostenlosen Überarbeitungen stellst du sicher, dass dein Baby Fotoalbum absolut perfekt ist, bevor es in Druck geht.</p>
  <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">Du wählst</h4>
            <p>Teil uns deinen gewünschten Fotobuchtyp und Albumdesignstil mit und lade deine Fotos hoch.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">Wir gestalten</h4>
            <p>Unsere Fotobuch Designer erwecken dein Album zum Leben. Überarbeitungen inklusive.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Zahle zum Drucken</h4>
            <p>Zahle erst, wenn du 100 % mit dem Design zufrieden bist  <br> (ohne Kaufverpflichtung). </p>
        </div>
    </div>
  <div class="section-service__buttons">
    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=2" class="button">BUCH STARTEN</a>
    <a href="<?php echo $this->languageUrl('static-howItWorks-') ?>" class="button button__light_border">MEHR ERFAHREN</a>
  </div>
</section>
<section class="section-album section-album_size-t">
  <div class="section-album__container">
    <h2 class="section-album__title">Baby Fotobücher Ideen</h2>
    <p class="section-album__entered">Arbeite mit unserem Designteam zusammen, um deinen ganz einzigartigen Stil zu kreieren. Oder stöber durch einige unserer beliebtesten Designs, ein Baby Fotobuch zu gestalten. </p>
    <div class="swiper-container swiperalbum ">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
            <picture data-priority="1" data-name="image_photobook_idea_1" data-path="2.6_baby_photo_books" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-image_photobook_idea_1.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/image_photobook_idea_1.jpg" alt="album with baby green">
            </picture>

          </figure>


          <h3 class="section-album__name-title">Emma<span>Baby Book</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_photobook_idea_2" data-path="2.6_baby_photo_books" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-image_photobook_idea_2.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/image_photobook_idea_2.jpg" alt="album with baby boy light">
            </picture>

          </figure>


          <h3 class="section-album__name-title">Ronan Cage<span>Baby Book</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_photobook_idea_3" data-path="2.6_baby_photo_books" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-image_photobook_idea_3.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/image_photobook_idea_3.jpg" alt="album with small baby light">
            </picture>

          </figure>


          <h3 class="section-album__name-title">Christian<span>Baby Book</span></h3>
        </div>
        <div class="swiper-slide">
          <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_photobook_idea_4" data-path="2.6_baby_photo_books" class="picture-webp">
              <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-image_photobook_idea_4.webp" type="image/webp">
              <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/image_photobook_idea_4.jpg" alt="album with sleepy baby">
            </picture>

          </figure>


          <h3 class="section-album__name-title">Chloe<span>Baby Book</span></h3>
        </div>
      </div>
      <div class="swiper-pagination swiperalbum-pagination"></div>
    </div>
    <div class="section-album__button">
      <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
    </div>
  </div>
</section>
<section class="description-img description-img__order">
  <div class="container">
    <div class="description-img__wrap">
      <div class="description-img__img">
        <figure style="padding-bottom: calc(631% / 788 * 100)" class="figure-webp">
          <picture data-priority="2" data-name="baby-album-gift" data-path="2.6_baby_photo_books" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/2.6_baby_photo_books/min-baby-album-gift.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.6_baby_photo_books/baby-album-gift.jpg" alt="Baby Fotobuch Geschenk für Grosseltern">
          </picture>

        </figure>


      </div>
      <div class="description-img__content">
        <h2 class="description-img__title">Das perfekte Geschenk</h2>
        <p>Stolze Grosseltern möchten keinen Moment verpassen, warum also nicht eine Fotobuch Babys erstes Jahr verschenken, ob Fotobuch Baby Junge oder Fotobuch Baby Mädchen. </p>
        <p>Bei uns kannst du exakte Kopien erhalten oder jedes Cover und einige der Inhalte anpassen lassen, um für Grosseltern oder einen Teil der Familie das perfekt personalisierte Geschenk zu machen.</p>
      </div>
    </div>
  </div>
</section>
<section class="section-video-content">
  <div class="section-video-content__container">
    <div class="section-video-content__video">
      <div class="lazy-video">
        <div class="lazy-video__preloader">
          <svg class="lazy-video__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
            <g fill="none" fill-rule="evenodd">
              <g transform="translate(1 1)" stroke-width="2">
                <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                <path d="M36 18c0-9.94-8.06-18-18-18">
                  <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                </path>
              </g>
            </g>
          </svg>
        </div>
        <div class="lazy-video__item "><iframe frameborder="0" class="lazy-video__activator-js" data-src="https://player.vimeo.com/video/574914550?background=1 " allow="autoplay; fullscreen; picture-in-picture" title="Premium Photo Books"></iframe>
        </div>
      </div>
    </div>
    <div class="section-video-content__content">
      <h2 class="section-video-content__title">Unsere Qualitätsgarantie</h2>
      <p>Wir stehen zu unseren Produkten und sind stolz auf Baby-Fotobücher, die deine Familie viele Jahre in Ehren halten kann. Wenn du mit der Qualität deines Albums nicht ganz zufrieden bist, lass es uns bitte wissen und wir bringen es in Ordnung.</p>
    </div>
  </div>
</section>
<section class="section-reviews">
  <div class="container">
    <h2 class="d-none"> reviews</h2>
    <?php echo $this->partial('application/partial/reviews') ?>
    <?php echo $this->partial('application/partial/reviews-box') ?>
  </div>
</section>
<div class="swiper-slide">
  <div class="section-reviews__slide">
    <div class="section-reviews__title">
      <strong>Kelly E</strong>
      <span>
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/badge_verified.png" alt="✓">
      </span>
    </div>
    <p class="section-reviews__text">Our album (lay flat, LG square, printed cover, padded + presentation box) as well as 6* pocket books all arrived VERY quickly, and were of excellent finish and quality. The entire process was hassle free, and the final album is exactly as we...</p>
    <time class="section-reviews__time">Posted 21h ago</time>
  </div>
</div>
<div class="swiper-slide">
  <div class="section-reviews__slide">
    <div class="section-reviews__title">
      <strong>Dede B</strong>
      <span>
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/icon-star.svg" alt="icon-star">
        <img src="/assets/images/badge_verified.png" alt="✓">
      </span>
    </div>
    <p class="section-reviews__text">Always a pleasure working with the team at PikPerfect. They are fast, friendly and very professional. I am always pleased with their services and my clients love their wedding albums.</p>
    <time class="section-reviews__time">Posted 2 days ago</time>
  </div>
</div>
</div>
</div>
<div class="swiper-button-next section-reviews__button-next"></div>
<div class="swiper-button-prev section-reviews__button-prev"></div>
</div>
</div>
</section>
<section class="section-text">
  <div class="section-text__container">
    <h2 class="section-text__title">Online ein Baby Fotobuch erstellen</h2>
    <div class="section-text__content">
      <p>Von goldigen Neugeborenenfotos bis hin zu ersten wackeligen Schritten lässt sich die einzigartige Entwicklung deines Kindes am besten in einem Fotoalbum Baby festhalten. Ein professioneller Babyfotobuch-Designer hilft dir, ein einzigartiges Fotobuch für Babys erstes Jahr zu erstellen.</p>
      <p>Wenn du dein Fotobuch drucken lassen willst <a target="_blank" href="<?php echo $this->languageUrl('static-photo-books-') ?>">kannst du über verschiedene hochwertige</a> Fotopapiere in Archivqualität das beste Baby Fotobuch für dein Budget erstellen. Wähle zwischen wunderschönem Leinen, geschmeidigem Leder oder einem bedruckten Einband mit personalisiertem Text. </p>
      <p>Hast du auch unglaublich viele Fotos deines Babys? Unsere talentierten Designer helfen dir dabei, das <a target="_blank" href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>">Fotobuch </a> ersten Lebensjahres deines Babys zu gestalten.</p>
      <p>Take advantage of unlimited free revisions to ensure your baby first year photo album, <a target="_blank" href="<?php echo $this->languageUrl('static-family-photo-albums-') ?>">family photo book</a> or <a target="_blank" href="<?php echo $this->languageUrl('static-travel-photo-books-') ?>">travel photo book</a> is tweaked to perfection and these fleeting moments get the attention they deserve.</p>
    </div>
  </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>