<?php
$this->headTitle('Pet Photo Books | Dog Photo Albums | PikPerfect');
$this->headMeta()->appendName('description', 'Create the perfect pet photo album for your little furry pals. Our talented designer will help create a beautifully designed pet album for you.');
$region = $this->region()->getUserRegion();
?>

<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="pet-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-pet-photo-books.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/pet-photo-books.jpg" alt="Dog photo book laying open on a table">
                </picture>

            </figure>


        </div>
        <div class="section-hero__content-col section-hero__content-col_blue-black">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <div class="section-hero__picture section-hero__picture_pet">
                <picture>
                    <source media="(max-width: 500px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">
                    <img src="/assets/images/towebp/2.11-pet-photo-books/illustration_hero_pet_books.svg" alt="picture hero fox">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Pet Photo Books</h1>
            <p>Create the perfect pet photo album with a little help from our experienced photo book design team.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__blue-dark">start now</a>
            <p class="price"><?php echo $this->translate('From') . ' ' . $this->format(
                                    $this->smallestPrices['photobook'],
                                    $region->iso,
                                    2,
                                    $region->symbol
                                ); ?></p>
        </div>
    </div>
</section>
<section class="section-text section-text_padding">
    <div class="section-text__container">
        <div class="section-text__content">
            <p>The unconditional love and loyalty from our furry pals or feathered friends brings joy to us every single day. Why not capture this love, and their sometimes quirky personality, in a personalized pet photo album?</p>
        </div>
    </div>
</section>
<section class="section-service section-service_big-cards">
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">You Choose</h4>
            <p>Select your preferred photobook type and album design style, upload your photos.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">We Design</h4>
            <p>Our expert photo book designers bring your album to life. Includes unlimited free revisions.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Pay to Print</h4>
            <p>Only pay when you’re 100% <br> satisfied with the design <br> (no commitment to purchase).</p>
        </div>
    </div>
</section>
<section class="section-img section-img_size-m">
    <div class="section-img__container">
        <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="pet-photo-albums" data-path="2.11-pet-photo-books" class="picture-webp">
                <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-pet-photo-albums.webp" type="image/webp">
                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/pet-photo-albums.jpg" alt="An open pet photo album showing a dog">
            </picture>

        </figure>


    </div>
</section>
<section class="section-img-text section-img-text_wrapper">
    <div class="section-img-text__container">
        <div class="section-img-text__wrap">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="pet-photo-album-books" data-path="2.11-pet-photo-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-pet-photo-album-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/pet-photo-album-books.jpg" alt="Custom designed pet photo book cover show dog and cat outlines">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <h2 class="section-img-text__title">Pet Photo Album Options</h2>
                    <p>We offer a number of different options for creating a dog photo book, or photo album for any of your pets. Our <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" target="_blank" class="link">layflat albums</a> are a popular option: developed on silver halide photo paper, these albums offer amazing print quality and uninterrupted double page spreads. If you’re looking for a more traditional book feel, our <a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" target="_blank" class="link"></a> photo books are a more economical option and can accommodate up to 240 pages.</p>
                </div>
            </div>
        </div>
        <div class="section-img-text__wrap section-img-text__wrap_order">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="Dog on pet photo book cover">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap" style="max-width: 370px;">
                    <p>If you’re interested in the very best for your furry friends, our <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" target="_blank" class="link">premium photo albums</a> offer thick layflat pages and a range of luxurious photo book cover options.</p>
                    <div class="section-img-text__button">
                        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button ">start now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-album section-album_size-xxl">
    <div class="section-album__container">
        <h2 class="section-album__title">Pet Photobook Design Inspiration</h2>
        <p class="section-album__entered">Collaborate with our team of designers to turn your pet photo album ideas into a creative project that will yield amazing results. Made from scratch, every pet photo album book is designed to match your style, and created with any combination of images, caption and design elements that best represent your pet’s place in your life. With unlimited free revisions, we make sure your pet book is perfect before sending it to print.</p>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Paw Patrol<span>Pet Books</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">The Purrfect Life<span>Pet Books</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">The Pup-parazzi Crew<span>Pet Books</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">When Enzo Adopted Us<span>Pet Books</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
        <div class="section-album__button">
            <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Ready to make a photo book for your pet?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__light section-transition__button section-transition__button_big" style="padding: 15px;">start now</a>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
    <div class="section-text__container section-text_big-container">
        <h2 class="section-text__title">Immortalize Your Pet in Print</h2>
        <div class="section-text__content">
            <p>It’s now easier than ever to create a pet memorial photo album for your furriest family member. Start off by choosing your favorite photos but also choose images that highlight some of the most memorable moments, like the time you caught them doing something naughty, or the loving look of support they offer when you’re having a bad day. Don’t forget to include photos of the everyday, as well their interactions with other family members or friends.</p>
            <p>Don’t hesitate to add your thoughts or favorite quotes about your pet, just send us the text you would like to include and we’ll make sure to design these into your big pet photo album. You may also want to include photos of paw prints, your kid’s drawing of the pet, or any other memento that would be meaningful in a <a href="<?php echo $this->languageUrl('static-photo-books-') ?>">printed photo book</a>.</p>
        </div>
    </div>
</section>
<?php echo $this->render('partial/quick_chat.phtml'); ?>