<?php
$this->headTitle('Fotoalbum vom Haustier | Tier Fotobuch | PikPerfect');
$this->headMeta()->appendName('description', 'Ob Hund, Katze, Maus oder Hamster: Die schönsten Momente mit deinem besten Freund verdienen es, in einem niedlichen Tier-Fotobuch verewigt zu werden.');
$region = $this->region()->getUserRegion();
?>

<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="pet-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-pet-photo-books.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/pet-photo-books.jpg" alt="Offenes Hunde Fotobuch auf Tisch">
                </picture>

            </figure>


        </div>
        <div class="section-hero__content-col section-hero__content-col_blue-black">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <div class="section-hero__picture section-hero__picture_pet">
                <picture>
                    <source media="(max-width: 500px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">
                    <img src="/assets/images/towebp/2.11-pet-photo-books/illustration_hero_pet_books.svg" alt="picture hero fox">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Fotobuch Haustier</h1>
            <p>Mit Hilfe unserer erfahrenen Fotobuch Designer das perfekte Tier Fotobuch gestalten.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__blue-dark">JETZT ANFANGEN</a>
            <p class="price"><?php echo $this->translate('From') . ' ' . $this->format(
                                    $this->smallestPrices['photobook'],
                                    $region->iso,
                                    2,
                                    $region->symbol
                                ); ?></p>
        </div>
    </div>
</section>
<section class="section-text section-text_padding">
    <div class="section-text__container">
        <div class="section-text__content">
            <p>Die bedingungslose Liebe und Loyalität unserer Vierbeiner bereitet uns jeden Tag Freude. Wie schön ist es, deren tierische Persönlichkeit in einem personalisierten Fotoalbum für Hund oder Katze festzuhalten?</p>
        </div>
    </div>
</section>
<section class="section-service section-service_big-cards">
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">Du wählst</h4>
            <p>Teil uns deinen gewünschten Fotobuchtyp und Albumdesignstil mit und lade deine Fotos hoch.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">Wir gestalten</h4>
            <p>Unsere Fotobuch Designer erwecken dein Album zum Leben. Überarbeitungen inklusive.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Zahle zum Drucken</h4>
            <p>Zahle erst, wenn du 100 % mit dem Design zufrieden bist  <br> (ohne Kaufverpflichtung). </p>
        </div>
    </div>
</section>
<section class="section-img section-img_size-m">
    <div class="section-img__container">
        <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="pet-photo-albums" data-path="2.11-pet-photo-books" class="picture-webp">
                <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-pet-photo-albums.webp" type="image/webp">
                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/pet-photo-albums.jpg" alt="Offenes Haustier Fotobuch mit Hund">
            </picture>

        </figure>


    </div>
</section>
<section class="section-img-text section-img-text_wrapper">
    <div class="section-img-text__container">
        <div class="section-img-text__wrap">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="pet-photo-album-books" data-path="2.11-pet-photo-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-pet-photo-album-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/pet-photo-album-books.jpg" alt="Individuell gestaltetes Haustier Fotobuch Einband mit Hund und Katzen Kontur">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <h2 class="section-img-text__title">Tier Fotoalbum gestalten</h2>
                    <p>Wir bieten verschiedene Möglichkeiten, ein Hunde Fotobuch oder Fotoalbum für Haustiere zu erstellen. Unser <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" target="_blank" class="link">Echtfotobuch </a>  ist eine beliebte Option: Die auf Silberhalogenid-Fotopapier entwickelten Seiten bieten erstaunliche Schärfe und nahtlose Doppelseiten. Das traditionelle Buchgefühl erhältst du mit einem kostengünstigeren  <a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" target="_blank" class="link">Fotobuch</a>Es bietet Platz für 1’000 Fotos auf 240 Seiten.</p>
                </div>
            </div>
        </div>
        <div class="section-img-text__wrap section-img-text__wrap_order">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="Hund auf Einband eines Haustier Fotobuchs">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap" style="max-width: 370px;">
                    <p>Wenn du das Beste für deinen tierischen Freund suchst, bieten unsere <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" target="_blank" class="link">Premium Fotoalben</a> dicke Echtfotoseiten und eine Reihe luxuriöser Fotobucheinbände.</p>
                    <div class="section-img-text__button">
                        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button ">JETZT STARTEN</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-album section-album_size-xxl">
    <div class="section-album__container">
        <h2 class="section-album__title">Fotobuch für Haustiere gestalten Ideen</h2>
        <p class="section-album__entered">Arbeite mit unserem Designteam zusammen, um deine Fotoalbum Ideen für Haustiere in ein kreatives Projekt zu verwandeln. Die Gestaltung wird nach deiner Vorstellung und mit Bildern, Texten und Designelementen erstellt, die den Platz deines Fellfreundes in deinem Leben am besten widerspiegeln. Unbegrenzte gratis Überarbeitungen inklusive, damit dein Haustierbuch perfekt ist, bevor es in Druck geht.</p>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Paw Patrol<span>Pet Books</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">The Purrfect Life<span>Pet Books</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">The Pup-parazzi Crew<span>Pet Books</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(300% / 289 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="dog-photo-books" data-path="2.11-pet-photo-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.11-pet-photo-books/min-dog-photo-books.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.11-pet-photo-books/dog-photo-books.jpg" alt="dog-photo-books">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">When Enzo Adopted Us<span>Pet Books</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
        <div class="section-album__button">
            <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Jetzt ein Haustier Fotoalbum erstellen?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=8" class="button button__light section-transition__button section-transition__button_big" style="padding: 15px;">FOTOBUCH ANFANGEN</a>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
    <div class="section-text__container section-text_big-container">
        <h2 class="section-text__title">Haustier Erinnerungsbuch drucken</h2>
        <div class="section-text__content">
            <p>Es ist jetzt einfacher denn je, ein Fotoalbum zur Erinnerung an dein vierbeiniges Familienmitglied zu erstellen. Suche deine Lieblingsfotos raus und auch Bilder, die einige besonders wichtige oder witzige Momente hervorheben: der typische Bettelblick, Lieblingsbeschäftigung, -spielzeug oder -aussichtsplatz, sowie Fotos des Alltags und Interaktionen mit anderen Familienmitgliedern oder Freunden.</p>
            <p>Füge gern deine Gedanken oder Lieblingszitate über dein Haustier hinzu, sende uns alles, und wir kümmern uns darum, dies in einem grossen Haustier-Fotoalbum zu gestalten. Besonders schön sind Fotos von Pfotenabdrücken, die Zeichnung deines Kindes vom Haustier oder andere Erinnerungsstücke, die in einem gedruckten  <a href="<?php echo $this->languageUrl('static-photo-books-') ?>">Fotobuch verewigt werden sollen</a>.</p>
        </div>
    </div>
</section>
<?php echo $this->render('partial/quick_chat.phtml'); ?>