<?php
$this->headTitle('Hochzeitsgästebuch | Fotobuch als Gästebuch | PikPerfect');
$this->headMeta()->appendName('description', 'Erstelle ein Fotobuch als Gästebuch im Stil deiner Hochzeit. Unser Designteam gestaltet ein Hochzeitsgästebuch individuell und genau nach deinen Wünschen.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="personalized-wedding-guest-books" data-path="2.10-wedding-guest-books" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-personalized-wedding-guest-books.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/personalized-wedding-guest-books.jpg" alt="Fotobuch Gästebuch für Hochzeit mit Fotos des Paares">
                </picture>

            </figure>


        </div>
        <div class="section-hero__content-col section-hero__content-col_khaki">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <h1 class="section-hero__size-title">Fotobuch Gästebuch</h1>
            <p>Unsere Designspezialisten helfen dir, ein einzigartiges Hochzeitsgästebuch mit Fotos zu erstellen.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=6" class="button button__khaki">JETZT ANFANGEN</a>
            <p class="price"><?php echo $this->translate('From') . ' ' . $this->format(
                                    $this->smallestPrices['photobook'],
                                    $region->iso,
                                    2,
                                    $region->symbol
                                ); ?></p>
        </div>
    </div>
</section>
<section class="section-text section-text_padding">
    <div class="section-text__container">
        <div class="section-text__content">
            <p>Haltet all die Emotionen eures schönsten Tages in einem Hochzeit Gästebuch fest, das mit lieben Wünschen von Familie und Freunden gefüllt ist. Unser personalisiertes Hochzeitsgästebuch enthält eure Lieblings Paarfotos zusammen mit viel Platz für handschriftliche Notizen eurer Gäste.</p>
        </div>
    </div>
</section>
<section class="section-service section-service_big-cards">
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">Du wählst</h4>
            <p>Teil uns deinen gewünschten Fotobuchtyp und Albumdesignstil mit und lade deine Fotos hoch.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">Wir gestalten</h4>
            <p>Unsere Fotobuchdesigner erwecken dein Album zum Leben. Überarbeitungen inklusive.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Zahle zum Drucken</h4>
            <p>Zahle erst, wenn du 100 % mit dem Design zufrieden bist <br>(ohne Kaufverpflichtung).</p>
        </div>
    </div>
</section>
<section class="section-img section-img_size-m">
    <div class="section-img__container">
        <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_wedding_guest_books" data-path="2.10-wedding-guest-books" class="picture-webp">
                <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_wedding_guest_books.webp" type="image/webp">
                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_wedding_guest_books.jpg" alt="wedding guest books">
            </picture>

        </figure>


    </div>
</section>
<section class="section-img-text">
    <div class="section-img-text__container">
        <div class="section-img-text__wrap">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="custom-wedding-guest-books" data-path="2.10-wedding-guest-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-custom-wedding-guest-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/custom-wedding-guest-books.jpg" alt="Individuell gestaltetes Gästebuch für Hochzeit mit Leinen Einband">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <h2 class="section-img-text__title">Gästebuch Hochzeit individuell gestalten</h2>
                    <p>Das Designteam von PikPerfect hilft, ein einzigartiges Fotobuch als Gästebuch erstellen, in dem die Glückwünsche von Familie und Freunden festgehalten und für die kommenden Jahre aufbewahrt werden. Unser <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" class="link" target="_blank">Echtfotobuch </a> ist beliebt, da es beeindruckende Doppelseiten ermöglicht, bei denen sowohl die Bilder als auch der Text über beide Seiten gehen können.</p>
                </div>
            </div>
        </div>
        <div class="section-img-text__wrap section-img-text__wrap_order">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="wedding-guest-signature-books" data-path="2.10-wedding-guest-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-wedding-guest-signature-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/wedding-guest-signature-books.jpg" alt="Gästebuch Hochzeit mit Unterschriften">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <p>Um ein Gästebuch auf Normalpapier zu drucken, empfehlen wir ein<a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" target="_blank" class="link">Hardcover Fotobuch.</a>Diese Fotobücher in robuster Klebebindung sind in verschiedenen Grössen und Gästebuch Einband Varianten erhältlich. Sie sind kostengünstiger, um eure Fotos zu präsentieren und Notizen von euren Lieblingsmenschen festzuhalten.</p>
                    <div class="section-img-text__button">
                        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=6" class="button ">JETZT STARTEN</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-album section-album_size-lx">
    <div class="section-album__container">
        <h2 class="section-album__title">Gästebuch gestalten Ideen</h2>
        <p class="section-album__entered">Arbeite mit unserem Team von Gästebuch Design Spezialisten zusammen, um etwas ganz Besonderes zu erschaffen. Jedes Gästebuch ist so gestaltet, dass es zu deinem Hochzeitsthema passt, und kann eine beliebige Kombination aus Fotos, Bildtexten und elegant gestalteten Bereichen für Notizen eurer Lieben enthalten. Mit unbegrenzten Überarbeitungen wird deine Gästebuch Gestaltung perfekt, bevor sie in Druck geht.</p>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="image_guest_book_inspo_1" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_1.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_1.jpg" alt="image guest book inspo-1">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For Your Eyes Only<span>Gästebuch zur Hochzeit</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="image_guest_book_inspo_2" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_2.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_2.jpg" alt="image guest book inspo-2">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Love you, Always!<span>Gästebuch zur Hochzeit</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="image_guest_book_inspo_3" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_3.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_3.jpg" alt="image guest book inspo-3">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For My Husband<span>Gästebuch zur Hochzeit</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="image_guest_book_inspo_4" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_4.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_4.jpg" alt="image guest book inspo-4">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Laced with Love<span>Gästebuch zur Hochzeit</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
        <div class="section-album__button">
            <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Jetzt ein Hochzeit Gästebuch erstellen? <br>
GÄSTEBUCH ANFANGE</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=6" class="button button__light section-transition__button section-transition__button_big">start now</a>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
    <div class="section-text__container section-text_big-container">
        <h2 class="section-text__title">Individuelle Hochzeits-Gästebücher mit WOW Effekt</h2>
        <div class="section-text__content">
            <p>Hochzeitsgästebücher erzählen die Geschichte eurer Beziehung und halten gleichzeitig die Liebe eurer Familie und Freunde fest. Wählt Bilder von eurem Verlobung Shooting oder den schönsten Momenten als Paar und wir zeigen sie in eurem Design, passend zu Hochzeitsfarbe und Hochzeitsstil.</p>
            <p>Ein grosses Hochzeitsgästebuch bietet viel Platz für Nachrichten und handschriftliche Notizen eurer engsten Freunde und Familie. Auch wenn die Hochzeit vorbei ist, sorgt unser professioneller  <a href="<?php echo $this->languageUrl('static-photo-books-') ?>" class="link" target="_blank">Fotobuch Druck</a> dafür, dass diese Worte ein Leben lang fortbestehen.</p>
            <p>Egal, ob du nach einem aussergewöhnlichen Fotobuch für Hochzeitsgäste suchst oder einem eleganten Gästebuch, das nur aus den besten Materialien hergestellt ist, lass unsere erfahrenen <a href="<?php echo $this->languageUrl('static-wedding-') ?>" class="link" target="_blank">Hersteller von Hochzeitsalben</a> ein Andenken fertigen, um diesen ganz besonderen Tag festzuhalten.</p>
        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>