<?php
$this->headTitle('Personalized Wedding Guest Book | Sign in Book | PikPerfect');
$this->headMeta()->appendName('description', 'Capture the love and emotion of your special day with a personalized wedding guest book filled with messages from your family and friends.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure style="padding-bottom: calc(505% / 880 * 100)" class="figure-webp">
                <picture data-priority="0" data-name="personalized-wedding-guest-books" data-path="2.10-wedding-guest-books" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-personalized-wedding-guest-books.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/personalized-wedding-guest-books.jpg" alt="Personalized wedding guest book with photos of couple">
                </picture>

            </figure>


        </div>
        <div class="section-hero__content-col section-hero__content-col_khaki">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <h1 class="section-hero__size-title">Wedding Guest Books</h1>
            <p>Our design specialists will help create a unique wedding guest book with photos, to last a lifetime.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=6" class="button button__khaki">start now</a>
            <p class="price"><?php echo $this->translate('From') . ' ' . $this->format(
                                    $this->smallestPrices['photobook'],
                                    $region->iso,
                                    2,
                                    $region->symbol
                                ); ?></p>
        </div>
    </div>
</section>
<section class="section-text section-text_padding">
    <div class="section-text__container">
        <div class="section-text__content">
            <p>Capture all the love and emotion of your special day with a wedding photo guest book filled with messages from your family and friends. Our personalized wedding guest books incorporate all your favorite couple photos, along with ample space for emotive, handwritten notes as it’s passed between your guests.</p>
        </div>
    </div>
</section>
<section class="section-service section-service_big-cards">
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">You Choose</h4>
            <p>Select your preferred photobook type and album design style, upload your photos.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">We Design</h4>
            <p>Our expert photo book designers bring your album to life. Includes unlimited free revisions.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Pay to Print</h4>
            <p>Only pay when you’re 100% <br> satisfied with the design <br> (no commitment to purchase).</p>
        </div>
    </div>
</section>
<section class="section-img section-img_size-m">
    <div class="section-img__container">
        <figure style="padding-bottom: calc(600% / 1376 * 100)" class="figure-webp">
            <picture data-priority="2" data-name="image_wedding_guest_books" data-path="2.10-wedding-guest-books" class="picture-webp">
                <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_wedding_guest_books.webp" type="image/webp">
                <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_wedding_guest_books.jpg" alt="wedding guest books">
            </picture>

        </figure>


    </div>
</section>
<section class="section-img-text">
    <div class="section-img-text__container">
        <div class="section-img-text__wrap">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="custom-wedding-guest-books" data-path="2.10-wedding-guest-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-custom-wedding-guest-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/custom-wedding-guest-books.jpg" alt="Custom wedding guest book with linen cover">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <h2 class="section-img-text__title">Personalized Wedding Guest Books</h2>
                    <p>PikPerfect’s design team will help create a unique wedding guest book in which the congratulatory messages from family and friends can be captured and preserved for the years to come. Our <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" class="link" target="_blank">layflat photo books</a> are a popular option as they allow for stunning double page spreads where both the images and text can span both pages.</p>
                </div>
            </div>
        </div>
        <div class="section-img-text__wrap section-img-text__wrap_order">
            <div class="section-img-text__img">
                <figure>
                    <picture data-priority="1" data-name="wedding-guest-signature-books" data-path="2.10-wedding-guest-books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-wedding-guest-signature-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/wedding-guest-signature-books.jpg" alt="Wedding photo guest book with signatures">
                    </picture>


                </figure>
            </div>
            <div class="section-img-text__content">
                <div class="section-img-text__content-wrap">
                    <p>If you’re looking for a guest book with photos printed on standard paper, we would recommend a <a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" target="_blank" class="link">hardcover photo book</a>. Available in multiple sizes and guest book cover options, these printed photo books are a more economical way to display your photos and capture notes from your favorite people.</p>
                    <div class="section-img-text__button">
                        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=6" class="button ">start now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-album section-album_size-lx">
    <div class="section-album__container">
        <h2 class="section-album__title">Guest Book Design Inspiration</h2>
        <p class="section-album__entered">Collaborate with our team of guest book design specialists to create something you’ll love. Created from scratch, every guest book is designed to match your wedding theme, and can have any combination of photos, captions and elegantly designed spaces for notes from your loved ones. With unlimited free revisions, we make sure your guest book design is perfect before it is sent to print.</p>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="image_guest_book_inspo_1" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_1.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_1.jpg" alt="image guest book inspo-1">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For Your Eyes Only<span>Wedding Guest Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="image_guest_book_inspo_2" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_2.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_2.jpg" alt="image guest book inspo-2">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Love you, Always!<span>Wedding Guest Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="image_guest_book_inspo_3" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_3.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_3.jpg" alt="image guest book inspo-3">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">For My Husband<span>Wedding Guest Book</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(362% / 362 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="image_guest_book_inspo_4" data-path="2.10-wedding-guest-books" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.10-wedding-guest-books/min-image_guest_book_inspo_4.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.10-wedding-guest-books/image_guest_book_inspo_4.jpg" alt="image guest book inspo-4">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Laced with Love<span>Wedding Guest Book</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
        <div class="section-album__button">
            <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Ready to make a Wedding Guest Book?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=6" class="button button__light section-transition__button section-transition__button_big">start now</a>
    </div>
</section>
<?php echo $this->partial('application/partial/why_choose_us') ?>
<section class="section-text section-text_white">
    <div class="section-text__container section-text_big-container">
        <h2 class="section-text__title">Personalized Wedding Guest Books that WOW</h2>
        <div class="section-text__content">
            <p>Wedding Guest Books tell the story of your courtship, while capturing the love from your family and friends. Select images from your engagement photo shoot or your most treasured moments as a couple, and we’ll display them in a design that matches your wedding color and style.</p>
            <p>Each of our large wedding guest books offers plenty of space for messages and handwritten notes from your closest friends and family, as it circulates among your guests on your special day. Once your wedding is over, our professional <a href="<?php echo $this->languageUrl('static-photo-books-') ?>" class="link" target="_blank">photo book printing services</a> ensure that these words will live on for a lifetime.</p>
            <p>Whether you’re after an unusual wedding guest photo book that can’t be bought off the shelf or an elegant guest book made from only the finest materials, let our expert <a href="<?php echo $this->languageUrl('static-wedding-') ?>" class="link" target="_blank">wedding album makers</a> craft a keepsake to document this most special of days for the years to come.</p>
        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>