<?php
$this->headTitle('Premium Fotoalbum | Hochwertiges Fotobuch | PikPerfect');
$this->headMeta()->appendName('description', 'Ein Luxus-Fotobuch gestalten. Hochwertige Einbände mit Leder oder Leinen und Prägung oder Gravur für das besondere Fotoalbum. Mit Qualitätsgarantie.');
$region = $this->region()->getUserRegion();
?>

<section class="section-hero">
    <div class="container">
        <div class="section-hero__grid">
            <div class="section-hero__left">
                <div thumbsSlider="" class="swiper-container section-hero__tab-activators">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="premium-photo-album-covers" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-premium-photo-album-covers.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/premium-photo-album-covers.jpg" alt="Beispiel Premium Fotobuch Einband">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="flush-mount-album" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-flush-mount-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/flush-mount-album.jpg" alt="Offenes Premium Fotoalbum auf Box">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="photo-album-thick" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-photo-album-thick.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/photo-album-thick.jpg" alt="Nahaufnahme Premium Fotobuch mit dicken Layflat Seiten ">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="glass-photo-album" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-glass-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/glass-photo-album.jpg" alt="Fotobuchcover mit Acrylglas">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="high-end-photo-books" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-high-end-photo-books.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/high-end-photo-books.jpg" alt="Frau hält Stapel mit Luxus Fotobüchern">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="position: relative;">
                                <img style="width: 100%; height:auto;" src="/assets/images/hero-tab-toggle-6.jpg" alt="Beispiel hochwertiges Fotobuch">
                                <img style="position: absolute; top:50% ; left:50%; transform: translate(-50%, -50%); pointer-events: none;" src="/assets/images/icons/button_play.svg">
                            </figure>
                        </div>
                    </div>
                </div>
                <div class="swiper-container section-hero__swiper">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="premium-photo-album-covers" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-premium-photo-album-covers.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/premium-photo-album-covers.jpg" alt="Beispiel Premium Fotobuch Einband">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="flush-mount-album" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-flush-mount-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/flush-mount-album.jpg" alt="Offenes Premium Fotoalbum auf Box">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="photo-album-thick" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-photo-album-thick.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/photo-album-thick.jpg" alt="Nahaufnahme Premium Fotobuch mit dicken Layflat Seiten ">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="glass-photo-album" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-glass-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/glass-photo-album.jpg" alt="Fotobuchcover mit Acrylglas">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="high-end-photo-books" data-path="2.1" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-high-end-photo-books.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/high-end-photo-books.jpg" alt="Frau hält Stapel mit Luxus Fotobüchern">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide hero-video-slide">
                            <div class="hero-video-slide__preloader">
                                <svg class="hero-video-slide__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
                                    <g fill="none" fill-rule="evenodd">
                                        <g transform="translate(1 1)" stroke-width="2">
                                            <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                                            <path d="M36 18c0-9.94-8.06-18-18-18">
                                                <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                                            </path>
                                        </g>
                                    </g>
                                </svg>
                            </div>

                            <div class="hero-video-slide__item"> <iframe frameborder="0" id="hero-video" src="" data-src="https://player.vimeo.com/video/569981023?background=1" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="@@titleVideo"></iframe>
                            </div>
                        </div>

                    </div>
                    <div class="section-hero__swiper-pagination"></div>
                </div>
            </div>
            <div class="section-hero__right">
                <h1 class="tab__title">Fotobuch hochwertig</h1>
                <p class="tab__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['premium'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="stars tab__starts">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <span><?php echo $this->reviewsCount()->getCount() ?> Bewertungen</span>
                </div>
                <p class="tab__text">Dieses Luxus Fotobuch hat dickes Layflat Papier, wunderschöne Panoramaseiten und verschiedene hochwertige Albumeinbände. Das Premium Fotoalbum ist dafür gemacht, die wichtigsten Momente ein Leben lang aufzubewahren, von den ersten Schritten deines Babys bis zu Jubiläen und anderen besonderen Anlässen.</p>
                <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'premium']) ?>" class="tab__button button">ALBUM MACHEN</a>
                <div class="tab__check">
                    <img loading="lazy" src="/assets/images/icon-check.svg" alt="icon-check" width="24" height="24">
                    <p>Qualitätsgarantie inklusive</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="1" data-name="flush-mount-photo-book" data-path="2.1" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-flush-mount-photo-book.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/flush-mount-photo-book.jpg" alt="Hochwertiges Fotoalbum mit dicken Layflatseiten">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Was ist ein Luxus Fotoalbum?</h2>
                <p>Unser Premium Layflat-Album, oft auch High-End Fotobuch genannt, wird auf Profi Fuji-Fotopapier entwickelt, das dann auf Karton "kaschiert" wird, um dicke Layflat-Seiten zu erhalten. Die nahtlosen Doppelseiten haben einen praktisch unsichtbaren Falz, was für eine atemberaubende Panoramaansicht deiner schönsten Fotos sorgt. Von unseren Buchbindern handgefertigt überdauert dieses Premium Fotobuch die Zeit mit Stil.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="luxury-photo-books" data-path="2.1" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-luxury-photo-books.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/luxury-photo-books.jpg" alt="Luxus Fotobücher von PikPerfect">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Besondere Fotobucheinbände</h2>
                <p>Hochwertige Fotobücher brauchen einen besonders schönen Einband: Ob weiches Leinen, echtes Leder oder ein Premium Fotoalbum mit Acrylglas Cover, wir haben eine grosse Auswahl für dich bereit.</p>
                <p>Alle Einbandmaterialien sind mit einer Prägung versehen, erhältlich in zwei Schriftarten und sechs Farben (Gold, Kupfer, Silber, weiss, schwarz, transparent). Eine Lasergravur auf dem Fotobuch-Cover und individuell geprägte Logos sind möglich.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="luxury-photo-albums" data-path="2.1" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-luxury-photo-albums.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/luxury-photo-albums.jpg" alt="Luxus Fotobuch auf Sofakissen">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Fotopapier in Archivqualität</h2>
                <p>PikPerfect-Premiumalben werden auf Archivfotopapier entwickelt, das dann auf einen weissen Karton aufgezogen wird, was zu wunderschönen nahtlosen Doppelseiten führt.</p>
                <p>Das Fuji Crystal Archive DP II Fotopapier bietet hervorragende Farben, natürliche Hauttöne und unglaubliche Details. Es ist immer eine ausgezeichnete Wahl (Glanz- oder Perlmuttfinish). Für den extra matten Look eines Fine-Art Albums wähle das Fujicolor Crystal Archive Professional Velvet-Papier, das einen atemberaubend weichen und tiefmatten Effekt bietet.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="luxury-photo-album-box" data-path="2.1" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.1/min-luxury-photo-album-box.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.1/luxury-photo-album-box.jpg" alt="Fotobuch mit Acrylglas in Geschenkbox">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Premium Geschenkverpackung</h2>
                <p>Eine passende Fotobuch Geschenkbox verleiht den perfekten letzten Schliff. Diese wunderschönen handgefertigten Schachteln haben einen Holzrahmen und den Stoff deiner Wahl, um deine wertvollen Erinnerungen ein Leben lang zu schützen.</p>
            </div>
        </div>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Willst du ein hochwertiges Fotobuch erstellen?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>" class="button button__light section-transition__button">JETZT STARTEN</a>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> bewertungen</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-accordion">
    <div class="container">
        <h2 class="section-accordion__title">Mehr über unsere Premium Fotoalben </h2>
        <div class="accordion">
            <div class="accordion__item">
                <h3 class="accordion__title">Wie dick sind die Seiten?</h3>
                <p class="accordion__text">Jede Seite eines hochwertigen Layflat-Fotobuchs ist etwa 1.1 mm dick, einschliesslich der weissen Einlage zwischen den Seiten. Bei maximal 76 Seiten ist das Album etwa 50 mm dick.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Wie lagere ich mein Album am besten?</h3>
                <p class="accordion__text">Wir empfehlen, dein Premium-Layflat-Album an einem trockenen Ort ohne direkte Sonneneinstrahlung aufzubewahren. Um ein Verziehen und übermässigen Druck auf die Bindung zu vermeiden, lagerst du das Album liegend, idealerweise in einer unserer Fotoalbumboxen.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Kann ich einen individuellen Fotobuchtitel hinzufügen?</h3>
                <p class="accordion__text">Alle hochwertigen Fotoalben aus Leinen und Leder beinhalten einen geprägten Titel (zweizeilig). Wir bieten auch individuell geprägte und lasergravierte Titel an, die mit einer Schriftart oder einem Logo deiner Wahl gestaltet werden können.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Ist ein PikPerfect-Logo auf meinem Album?</h3>
                <p class="accordion__text">Unsere Premium-Fotobücher haben kein Branding, aber der Versandkarton und die beigefügte Handelsrechnung enthalten das PikPerfect-Logo.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Wie viele Seiten und Fotos kann ich maximal verwenden?</h3>
                <p class="accordion__text">Unsere Premium-Layflat-Fotobücher haben maximal 76 Seiten und können bis zu ca. 300 Fotos enthalten. Für mehr Fotos empfehlen wir, stattdessen ein <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" target="_blank" class="link">Layflat-Echtfotobuch</a> oder ein<a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" target="_blank" class="link">Hardcover-Fotobuch</a>  zu wählen.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Welches Albumpapier ist das Beste?</h3>
                <p class="accordion__text">Das Fuji Velvet-Papier hat ein tiefmattes Finish, während das Fuji Archive DPII-Papier (glänzend oder perlmutt) unsere beliebteste Option ist, da es lebendigere Farben und mehr Tiefe bietet. Erfahre mehr über unseren <a href="<?php echo $this->languageUrl('static-photo-books-') ?>" target="_blank" class="link">Fotobuch-Druck</a> um zu entscheiden, welches Papier für dich am besten ist.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Wie lang ist die Produktionszeit?</h3>
                <p class="accordion__text">Unsere Premium-Layflat-Alben werden mit der Sorgfalt und Aufmerksamkeit handgefertigt, die deine Fotos verdienen. Wir sind stolz auf schnelle Bearbeitungszeiten (9-12 Werktage) und bieten gleichzeitig einen erschwinglichen Pauschalversand zu Zielen auf der ganzen Welt.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Was ist ein Fotoalbum mit Acrylglas?</h3>
                <p class="accordion__text">Auch Fotobuch mit Glascover genannt, denn diese hochwertigen Fotobücher haben einen kristallklaren Acryleinband, der dein Titelbild in seiner ganzen Brillanz hervorhebt. Um den Buchrücken wird wahlweise veganes Leder oder Leinen gewickelt.</p>
            </div>
        </div>
    </div>
</section>
