<?php
$this->headTitle('Familienfotoalbum & Familienfotobuch erstellen | PikPerfect');
$this->headMeta()->appendName('description', 'Ein Familienalbum gestalten war noch nie so einfach: Unsere Designer erstellen ein wertvolles Familien-Fotobuch für dich. Mit Qualitätsgarantie.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure class="figure-webp">
                <picture data-priority="0" data-name="family-photo-album" data-path="2.4_family_photo_albums" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photo-album.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photo-album.jpg" alt="Frau schaut Familienfotoalbum an">
                </picture>


            </figure>
        </div>
        <div class="section-hero__content-col section-hero__content-col_light-orange">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <div class="section-hero__picture">
                <picture>
                    <source media="(max-width: 500px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">
                    <img src="/assets/images/towebp/2.4_family_photo_albums/illustration_pandas.png" alt="picture panda">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Fotobuch Familie</h1>
            <p>Unsere Designexperten verewigen deine schönsten Momente in einem hochwertigen Familienfotobuch.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=3" class="button button__light-orange-opacity">start now</a>
            <p class="small">No advance payment required</p>
        </div>
    </div>
</section>
<section class="dignity dignity_blocks">
    <div class="dignity__container">
        <div class="dignity__wrap">
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_the_human_touch.svg" alt="circle_the_human_touch">
                </div>
                <div class="dignity__content">
                    <h3>Die persönliche Note</h3>
                    <p> Wir helfen die besten Fotos auswählen und gestalten das Album mit dir.</p>
                </div>
            </div>
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_attention_to_detail.svg" alt="circle_attention_to_detail">
                </div>
                <div class="dignity__content">
                    <h3>Liebe zum Detail</h3>
                    <p>Jedes Fotobuch wird vor dem Druck geprüft und danach sorgfältig verpackt.</p>
                </div>
            </div>
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_premium_materials.svg" alt="circle_premium_materials">
                </div>
                <div class="dignity__content">
                    <h3>Premium Materialien</h3>
                    <p>Gefertigt mit den hochwertigsten Einbänden und Papieren.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="description-img__container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <div class="swiper-container swiperDescription">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="premium-family-photo-album" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-premium-family-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/premium-family-photo-album.jpg" alt="hochwertiges Fotobuch mit Familienfotos">
                                </picture>

                            </figure>

                        </div>
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="premium-family-photo-book" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-premium-family-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/premium-family-photo-book.jpg" alt="Familienfotoalbum auf Regal">
                                </picture>

                            </figure>

                        </div>
                    </div>
                    <div class="swiperDescription-pagination"></div>
                </div>
            </div>
            <div class="description-img__content description-img__content_padding">
                <h2 class="description-img__title"><span>Unsere Luxuslinie</span> Premium Layflat Familienalbum</h2>
                <p>Mit steifen, komplett flach liegenden Echtfotoseiten, einer grossen Auswahl an Premium-Einbandoptionen und Fotopapieren in Archivqualität stellen sie unsere hochwertigsten Familienfotoalben dar. Diese handgefertigten Fotobücher mit Luxus-Finish und brillanter Farbqualität liegen schwer und elegant in den Händen.</p>
                <p> So bewahrst du deine schönsten Familienerinnerungen mit extra viel Stil auf.</p>
                <p class="description-img__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['layflat'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="description-img__buttons">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'premium']) ?>?occasion=3" class="button">order</a>
                    <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" class="button button__gray">explore</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="description-img__container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <div class="swiper-container swiperDescription">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-family-photo-album" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-layflat-family-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/layflat-family-photo-album.jpg" alt="Familienfotoalbum für Eltern mit Baby">
                                </picture>

                            </figure>

                        </div>
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="layflat-family-album" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-layflat-family-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/layflat-family-album.jpg" alt="Fotobuch Familie mit Layflat Seiten">
                                </picture>

                            </figure>

                        </div>
                    </div>
                    <div class="swiperDescription-pagination"></div>
                </div>
            </div>
            <div class="description-img__content description-img__content_padding">
                <h2 class="description-img__title"><span>Unser Bestseller</span>Layflat <br> Familienfotoalbum  </h2>
                <p>Unsere Familien-Fotobücher mit Layflat-Bindung werden auf Fuji Fotopapier mit Perlmatt- oder Glanz-Finish entwickelt und ermöglichen nahtlose Doppelseiten deiner schönsten Familienmomente.</p>
                <p>Mit einem erschwinglichen Preis ohne Kompromisse bei der Qualität sind sie für viele Menschen eines der besten Familienfotoalben.</p>
                <p class="description-img__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['layflat'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="description-img__buttons">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'layflat']) ?>?occasion=3" class="button">BESTELLEN </a>
                    <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" class="button button__gray">MEHR ERFAHREN</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="description-img__container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <div class="swiper-container swiperDescription">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="family-photo-book" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photo-book.jpg" alt="offenes Familienfotoalbum mit Kinderfotos">
                                </picture>

                            </figure>

                        </div>
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="family-photobook" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photobook.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photobook.jpg" alt="Ansicht Familienfotobuch Bindung">
                                </picture>

                            </figure>

                        </div>
                    </div>
                    <div class="swiperDescription-pagination"></div>
                </div>
            </div>
            <div class="description-img__content description-img__content_padding">
                <h2 class="description-img__title"><span>Unser Klassiker </span>      Familienfotobuch   </h2>
                <p>Digital gedruckt auf mattem oder glänzendem Fotopapier und mit bis zu 244 Seiten bietet das Familienjahrbuch von PikPerfect Platz für bis zu 1’000 Fotos.</p>
                <p>P Professionell gedruckt und gebunden von unseren erfahrenen Buchbindern, sind sie das perfekte Jahresrückblick Fotobuch, um die wichtigsten Erinnerungen für Jahrzehnte zu bewahren.</p>
                <p class="description-img__price"><?php echo $this->translate('From') . ' ' .
                                        $this->format(
                                            $this->smallestPrices['photobook'],
                                            $region->iso,
                                            2,
                                            $region->symbol) ?></p>
                <div class="description-img__buttons">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=3" class="button">BESTELLEN </a>
                    <a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" class="button button__gray">MEHR ERFAHREN</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-img">
    <figure style="padding-bottom: calc(724% / 1440 * 100)" class="figure-webp">
        <picture data-priority="2" data-name="family-photo-album-book" data-path="2.4_family_photo_albums" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photo-album-book.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photo-album-book.jpg" alt="Familienfotoalbum auf Regal">
        </picture>

    </figure>


</section>
<section class="section-service">
    <h2 class="section-service__title">Familienalbum gestalten</h2>
    <p class="section-service__entered">Es war noch nie so einfach, ein individuelles Familienfotoalbum zu erstellen: Lade einfach deine Fotos hoch, unser Designteam erledigt den Rest! Mit dem optionalen Fotoauswahlservice und unbegrenzten gratis Überarbeitungen stellen unsere Fotobuchexperten sicher, dass dein Familienalbum perfekt gestaltet ist, bevor es in Druck geht. </p>
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">Du wählst</h4>
            <p>Teil uns deinen gewünschten Fotobuchtyp und Albumdesignstil mit und lade deine Fotos hoch.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">Wir gestalten</h4>
            <p>Unsere Fotobuch Designer erwecken dein Album zum Leben. Überarbeitungen inklusive.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Zahle zum Drucken</h4>
            <p>Zahle erst, wenn du 100 % mit dem Design zufrieden bist  <br> (ohne Kaufverpflichtung). </p>
        </div>
    </div>
    <div class="section-service__buttons">
        <a href="<?php echo $this->languageUrl('upload-photos-') ?>?occasion=3" class="button">BUCH STARTEN</a>
        <a href="<?php echo $this->languageUrl('static-howItWorks-') ?>" class="button button__light_border">MEHR ERFAHREN</a>
    </div>
</section>
<section class="section-album section-album_size-t">
    <div class="section-album__container">
        <h2 class="section-album__title">Ideen für Familienfotoalben</h2>
        <p class="section-album__entered">Stöbere durch einige unserer beliebtesten Designstile für Familienfotobücher. Oder arbeite mit unserem Designteam zusammen, um deinen ganz einzigartigen Stil zu kreieren.</p>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="album_2021_adventures" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_2021_adventures.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_2021_adventures.jpg" alt="album 2021 adventures">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">2021 Adventures<span>Family Album</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="album_life_in_pictures" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_life_in_pictures.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_life_in_pictures.jpg" alt="album life in pictures">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Life in Pictures<span>Family Album</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="album_love_joy_2020" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_love_joy_2020.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_love_joy_2020.jpg" alt="album love joy 2020">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Love & Joy 2020<span>Family Album</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="album_hello_adventure" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_hello_adventure.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_hello_adventure.jpg" alt="album hello adventure">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Hello, Adventures!<span>Family Album</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
        <div class="section-album__button">
            <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
        </div>
    </div>
</section>
<section class="description-img description-img__order description-img_half">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(800% / 680 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="linen-family-photo-albums" data-path="2.4_family_photo_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-linen-family-photo-albums.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/linen-family-photo-albums.jpg" alt="Familienfotobuch mit Leineneinband">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Kleinere Fotobuch-Kopien</h2>
                <p>Kleinere Exemplare deines jährlichen Fotobuchs lassen dich die schönen Zeiten mit dem Rest deiner Familie teilen.</p>
                <p>Bei uns kannst du jedes Cover und einige der Inhalte anpassen lassen, um für die Grosseltern oder einen bestimmten Teil der Familie das perfekt personalisierte Geschenk zu erhalten.</p>
                <div class="description-img__buttons description-img__buttons_big">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=3" class="button button__big">BUCH ERSTELLEN</a>
                    <a href="<?php echo $this->languageUrl('gift-vouchers-') ?>" class="button button__gray">GUTSCHEIN </a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-video-content">
    <div class="section-video-content__container">
        <div class="section-video-content__video">
            <div class="lazy-video">
                <div class="lazy-video__preloader">
                    <svg class="lazy-video__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
                        <g fill="none" fill-rule="evenodd">
                            <g transform="translate(1 1)" stroke-width="2">
                                <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                                <path d="M36 18c0-9.94-8.06-18-18-18">
                                    <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                                </path>
                            </g>
                        </g>
                    </svg>
                </div>
                <div class="lazy-video__item "><iframe frameborder="0" class="lazy-video__activator-js" data-src="https://player.vimeo.com/video/574888486?background=1 " allow="autoplay; fullscreen; picture-in-picture" title="premium-photo-book.mp4"></iframe>
                </div>
            </div>
        </div>
        <div class="section-video-content__content">
            <h2 class="section-video-content__title">Unsere Qualitätsgarantie</h2>
            <p>Wir stehen zu unseren Produkten und sind stolz auf Fotoalben, die deine Familie viele Jahre in Ehren halten kann. Wenn du mit der Qualität deines Albums nicht ganz zufrieden bist, lass es uns bitte wissen und wir bringen es in Ordnung.</p>
        </div>
    </div>
</section>
<section class="section-text">
    <div class="section-text__container">
        <h2 class="section-text__title">Online ein Familienfotoalbum erstellen</h2>
        <div class="section-text__content">
            <p>Ob Geburtstagsfeier, Familienurlaub oder persönliches Geschenk zum Muttertag oder Vatertag, unsere Familienfotobücher sind ideal, um die wichtigsten Momente aufzubewahren und mit Freunden und Verwandten zu teilen. Unsere erfahrenen Designer zaubern ein massgeschneidertes Andenken, erwecken deine Ideen zum Leben.</p>
            <p>Unser Familienfotobuch kann mit verschiedenen Fotopapieren und Einbänden hergestellt werden, so dass unse <a target="_blank" href="<?php echo $this->languageUrl('static-photo-books-') ?>">Online-Fotobuch</a> Druckservice für jedes Budget etwas bietet. Ob elegantes Leinen oder geschmeidiges Leder, wir personalisieren jeden Einband mit deiner bevorzugten Farbe und einem individuellen Titel. </p>
            <p>Überwältigt dich die Masse deiner Fotos und du weisst nicht, wo du anfangen sollst? Unser Fotoauswahlservice hilft, Tausende Fotos zu sortieren und sendet dir eine Vorauswahl zu. Du prüfst diese ganz einfach online und machst letzte Anpassungen, falls nötig. Anschliessend beginnen wir mit der individuellen<a target="_blank" href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>">Gestaltung deines Fotobuchs. </a>Alle Designs beinhalten unbegrenzte kostenlose Überarbeitungen, damit du mit der Gestaltung absolut zufrieden bist, bevor das Album in Druck geht.
 </p>
        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>