<?php
$this->headTitle('Family Photo Albums & Family Photo Books | PikPerfect');
$this->headMeta()->appendName('description', 'Making a family photo album has never been easier. Upload your photos and our design specialist will do the rest. Includes unlimited free revisions.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero__image-left">
    <div class="section-hero__wrap-flex">
        <div class="section-hero__image-col px-0">
            <figure class="figure-webp">
                <picture data-priority="0" data-name="family-photo-album" data-path="2.4_family_photo_albums" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photo-album.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photo-album.jpg" alt="Women viewing family photo album">
                </picture>


            </figure>
        </div>
        <div class="section-hero__content-col section-hero__content-col_light-orange">
            <div class="section-hero__bg">
                <picture data-priority="0" data-name="image_texture" data-path="" class="picture-webp">
                    <source class="toggle-img--js" srcset="/assets/images/towebp//min-image_texture.webp" type="image/webp">
                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp//image_texture.jpg" alt="bg-hero">
                </picture>


            </div>
            <div class="section-hero__picture">
                <picture>
                    <source media="(max-width: 500px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">
                    <img src="/assets/images/towebp/2.4_family_photo_albums/illustration_pandas.png" alt="picture panda">
                </picture>
            </div>
            <h1 class="section-hero__size-title">Family Photo Albums</h1>
            <p>Our design specialists will help document your treasured moments in a beautiful family photo book.</p>
            <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=3" class="button button__light-orange-opacity">start now</a>
            <p class="small">No advance payment required</p>
        </div>
    </div>
</section>
<section class="dignity dignity_blocks">
    <div class="dignity__container">
        <div class="dignity__wrap">
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_the_human_touch.svg" alt="circle_the_human_touch">
                </div>
                <div class="dignity__content">
                    <h3>The Human Touch</h3>
                    <p>We help choose the best photos and design the album with you.</p>
                </div>
            </div>
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_attention_to_detail.svg" alt="circle_attention_to_detail">
                </div>
                <div class="dignity__content">
                    <h3>Attention to Detail</h3>
                    <p>Every album is manually checked before print and carefully packaged.</p>
                </div>
            </div>
            <div class="dignity__block">
                <div class="dignity__img">
                    <img src="/assets/images/circle_premium_materials.svg" alt="circle_premium_materials">
                </div>
                <div class="dignity__content">
                    <h3>Premium Materials</h3>
                    <p>Assembled with only the highest quality covers and papers.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="description-img__container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <div class="swiper-container swiperDescription">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="premium-family-photo-album" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-premium-family-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/premium-family-photo-album.jpg" alt="Premium photo album with family photos">
                                </picture>

                            </figure>

                        </div>
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="premium-family-photo-book" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-premium-family-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/premium-family-photo-book.jpg" alt="Family photo album book on shelf">
                                </picture>

                            </figure>

                        </div>
                    </div>
                    <div class="swiperDescription-pagination"></div>
                </div>
            </div>
            <div class="description-img__content description-img__content_padding">
                <h2 class="description-img__title"><span>Our Luxury Line</span>Premium Layflat Family Album</h2>
                <p>Featuring thick, layflat pages and a wide range of premium cover options, these archival family photo albums are the perfect way to turn those special moments into memories that will last a lifetime.</p>
                <p>Handcrafted for a luxurious finish, and developed on professional grade photo papers, these premium family photo books preserve your memories in style.</p>
                <p class="description-img__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['layflat'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="description-img__buttons">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'premium']) ?>?occasion=3" class="button">order</a>
                    <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>" class="button button__gray">explore</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="description-img__container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <div class="swiper-container swiperDescription">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="layflat-family-photo-album" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-layflat-family-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/layflat-family-photo-album.jpg" alt="Family photo album showing couple with baby">
                                </picture>

                            </figure>

                        </div>
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="layflat-family-album" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-layflat-family-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/layflat-family-album.jpg" alt="Family photo album with layflat pages">
                                </picture>

                            </figure>

                        </div>
                    </div>
                    <div class="swiperDescription-pagination"></div>
                </div>
            </div>
            <div class="description-img__content description-img__content_padding">
                <h2 class="description-img__title"><span>Our Bestseller</span>Layflat Family <br> Photo Album</h2>
                <p>Developed on Fuji photo paper with either a Pearl Matte or Gloss finish, our layflat family photo album books allow you to display uninterrupted double page spreads of your most-loved family moments.</p>
                <p>Offering an affordable price tag without compromising on quality, these are one of the best family photo albums online for most people.</p>
                <p class="description-img__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['layflat'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="description-img__buttons">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'layflat']) ?>?occasion=3" class="button">order</a>
                    <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>" class="button button__gray">explore</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="description-img__container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <div class="swiper-container swiperDescription">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="family-photo-book" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photo-book.jpg" alt="Open family photo album with photos of kids">
                                </picture>

                            </figure>

                        </div>
                        <div class="swiper-slide">
                            <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="family-photobook" data-path="2.4_family_photo_albums" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photobook.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photobook.jpg" alt="View of family photo book binding">
                                </picture>

                            </figure>

                        </div>
                    </div>
                    <div class="swiperDescription-pagination"></div>
                </div>
            </div>
            <div class="description-img__content description-img__content_padding">
                <h2 class="description-img__title"><span>Our Everyday Classic</span>Family <br> Photo Book</h2>
                <p>Digitally printed on matte or lustre photo paper and with up to 244 pages, PikPerfect’s family yearbook can hold up to approximately 1,000 photos.</p>
                <p>Professionally printed and bound by our skilled book makers, these make for the perfect annual photo book to display all of your most important memories for many years to come.</p>
                <p class="description-img__price"><?php echo $this->translate('From') . ' ' .
                                        $this->format(
                                            $this->smallestPrices['photobook'],
                                            $region->iso,
                                            2,
                                            $region->symbol) ?></p>
                <div class="description-img__buttons">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=3" class="button">order</a>
                    <a href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>" class="button button__gray">explore</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-img">
    <figure style="padding-bottom: calc(724% / 1440 * 100)" class="figure-webp">
        <picture data-priority="2" data-name="family-photo-album-book" data-path="2.4_family_photo_albums" class="picture-webp">
            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-family-photo-album-book.webp" type="image/webp">
            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/family-photo-album-book.jpg" alt="Family photo album book on shelf">
        </picture>

    </figure>


</section>
<section class="section-service">
    <h2 class="section-service__title">Family Yearbook Design</h2>
    <p class="section-service__entered">Making a personalized family photo album has never been easier: just upload your photos and let our design team do the rest! With an optional photo selection service and unlimited free revisions, our album design specialists will work with you to ensure your family album is perfect before it’s sent to print.</p>
    <div class="section-service__cards">
        <div class="section-service__card">
            <h3 class="section-service__number">1.</h3>
            <h4 class="section-service__name-service">You Choose</h4>
            <p>Select your preferred photobook type and album design style, upload your photos.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">2.</h3>
            <h4 class="section-service__name-service">We Design</h4>
            <p>Our expert photo book designers bring your album to life. Includes unlimited free revisions.</p>
        </div>
        <div class="section-service__card">
            <h3 class="section-service__number">3.</h3>
            <h4 class="section-service__name-service">Pay to Print</h4>
            <p>Only pay when you’re 100% <br> satisfied with the design <br> (no commitment to purchase).</p>
        </div>
    </div>
    <div class="section-service__buttons">
        <a href="<?php echo $this->languageUrl('upload-photos-') ?>?occasion=3" class="button">START book</a>
        <a href="<?php echo $this->languageUrl('static-howItWorks-') ?>" class="button button__light_border">learn more</a>
    </div>
</section>
<section class="section-album section-album_size-t">
    <div class="section-album__container">
        <h2 class="section-album__title">Family Photo Album Ideas</h2>
        <p class="section-album__entered">Browse through some of our most popular family photo book design styles. <br> Or work with our design team to create one that is entirely unique to your style.</p>
        <div class="swiper-container swiperalbum ">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="1" data-name="album_2021_adventures" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_2021_adventures.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_2021_adventures.jpg" alt="album 2021 adventures">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">2021 Adventures<span>Family Album</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="album_life_in_pictures" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_life_in_pictures.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_life_in_pictures.jpg" alt="album life in pictures">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Life in Pictures<span>Family Album</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="album_love_joy_2020" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_love_joy_2020.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_love_joy_2020.jpg" alt="album love joy 2020">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Love & Joy 2020<span>Family Album</span></h3>
                </div>
                <div class="swiper-slide">
                    <figure style="padding-bottom: calc(330% / 330 * 100)" class="figure-webp">
                        <picture data-priority="2" data-name="album_hello_adventure" data-path="2.4_family_photo_albums" class="picture-webp">
                            <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-album_hello_adventure.webp" type="image/webp">
                            <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/album_hello_adventure.jpg" alt="album hello adventure">
                        </picture>

                    </figure>


                    <h3 class="section-album__name-title">Hello, Adventures!<span>Family Album</span></h3>
                </div>
            </div>
            <div class="swiper-pagination swiperalbum-pagination"></div>
        </div>
        <div class="section-album__button">
            <a href="<?php echo $this->languageUrl('static-photo-book-samples-') ?>" class="button button__light_border">view more</a>
        </div>
    </div>
</section>
<section class="description-img description-img__order description-img_half">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(800% / 680 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="linen-family-photo-albums" data-path="2.4_family_photo_albums" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.4_family_photo_albums/min-linen-family-photo-albums.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.4_family_photo_albums/linen-family-photo-albums.jpg" alt="Family photo album with linen covers">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Smaller Duplicates</h2>
                <p>The perfect gift, smaller duplicates of your annual photo book allow you to share the good times with the rest of your family.</p>
                <p>You can choose to make exact duplicates or customize each cover and some of the content to focus on the grandparents or a particular part of the family.</p>
                <div class="description-img__buttons description-img__buttons_big">
                    <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>?occasion=3" class="button button__big">MAKE BOOK</a>
                    <a href="<?php echo $this->languageUrl('gift-vouchers-') ?>" class="button button__gray">GIFT CARDS</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-video-content">
    <div class="section-video-content__container">
        <div class="section-video-content__video">
            <div class="lazy-video">
                <div class="lazy-video__preloader">
                    <svg class="lazy-video__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
                        <g fill="none" fill-rule="evenodd">
                            <g transform="translate(1 1)" stroke-width="2">
                                <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                                <path d="M36 18c0-9.94-8.06-18-18-18">
                                    <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                                </path>
                            </g>
                        </g>
                    </svg>
                </div>
                <div class="lazy-video__item "><iframe frameborder="0" class="lazy-video__activator-js" data-src="https://player.vimeo.com/video/574888486?background=1 " allow="autoplay; fullscreen; picture-in-picture" title="premium-photo-book.mp4"></iframe>
                </div>
            </div>
        </div>
        <div class="section-video-content__content">
            <h2 class="section-video-content__title">Our Quality Guarantee</h2>
            <p>We stand by our products and take great pride in making photo albums your family can cherish for the years to come. If you are not entirely satisfied with the quality of your album, please let us know and we’ll be sure to make things right.</p>
        </div>
    </div>
</section>
<section class="section-text">
    <div class="section-text__container">
        <h2 class="section-text__title">Making a Family Photo Album online</h2>
        <div class="section-text__content">
            <p>Whether it's documenting your child’s birthday parties or family vacation, our custom family photo books are the ideal way to showcase the moments that mean the most. Our skilled designers will work their magic to bring your ideas to life and create a bespoke memento that can be shared with friends and relatives.</p>
            <p>Crafted using a selection of different photo papers and album covers, our <a target="_blank" href="<?php echo $this->languageUrl('static-photo-books-') ?>">online photo book</a> printing service allows you to create a family memory book that meets every budget. Whether you want an elegant linen or soft and supple leather, we can personalize each cover with your preferred color and custom title. </p>
            <p>Are you drowning in photos and don’t know where to start? Our Photo Selection Service will help sort through the thousands of photos you’ve taken through the year and then send you a shortlist of the most memorable ones. It’s easy to review and make any needed changes to the selection, after which we start with the design of your <a target="_blank" href="<?php echo $this->languageUrl('static-custom-photo-books-') ?>">custom photo book</a>. All designs include unlimited free revisions, so we make sure you are completely happy with the design before the album is sent to print. </p>
        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>