<?php
$this->headTitle('Custom Photo Books | Personalized Photo Albums | PikPerfect');
$this->headMeta()->appendName('description', 'Make a personalized photo book to preserve your most precious memories. WIth multiple paper and cover options, these make for the best photo books.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero">
    <div class="container">
        <div class="section-hero__grid">
            <div class="section-hero__left">
                <div thumbsSlider="" class="swiper-container section-hero__tab-activators">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="custom-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-book.jpg" alt="linen custom photo book with white embossed title">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="personalized-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-personalized-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/personalized-photo-album.jpg" alt="personalized photo album open flat">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="hardcover-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-hardcover-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/hardcover-photo-book.jpg" alt="hardcover phtoto book with family on cover">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="custom-photo-album-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album-book.jpg" alt="orange custom photo album book open">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="custom-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album.jpg" alt="custom designed photo album in a black box">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="position: relative;">
                                <img style="width: 100%; height:auto;" src="/assets/images/hero-tab-toggle-6.jpg" alt="Flush Mount album example">
                                <img style="position: absolute; top:50% ; left:50%; transform: translate(-50%, -50%); pointer-events: none;" src="/assets/images/icons/button_play.svg">
                            </figure>
                        </div>
                    </div>
                </div>
                <div class="swiper-container section-hero__swiper">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="custom-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-book.jpg" alt="linen custom photo book with white embossed title">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="personalized-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-personalized-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/personalized-photo-album.jpg" alt="personalized photo album open flat">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="hardcover-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-hardcover-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/hardcover-photo-book.jpg" alt="hardcover phtoto book with family on cover">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="custom-photo-album-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album-book.jpg" alt="orange custom photo album book open">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="custom-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album.jpg" alt="custom designed photo album in a black box">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide hero-video-slide">
                            <div class="hero-video-slide__preloader">
                                <svg class="hero-video-slide__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
                                    <g fill="none" fill-rule="evenodd">
                                        <g transform="translate(1 1)" stroke-width="2">
                                            <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                                            <path d="M36 18c0-9.94-8.06-18-18-18">
                                                <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                                            </path>
                                        </g>
                                    </g>
                                </svg>
                            </div>

                            <div class="hero-video-slide__item"> <iframe frameborder="0" id="hero-video" src="" data-src="https://player.vimeo.com/video/569978045?background=1" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Photo Books | PikPerfect"></iframe>
                            </div>
                        </div>

                    </div>
                    <div class="section-hero__swiper-pagination"></div>
                </div>
            </div>
            <div class="section-hero__right">
                <h1 class="tab__title">Custom Photo Books</h1>
                <p class="tab__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['photobook'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="stars tab__starts">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <span><?php echo $this->reviewsCount()->getCount() ?> reviews</span>
                </div>
                <p class="tab__text">Whether it's a family vacation or special milestone, making your own custom photo book is the perfect way to preserve these special memories. Available in five sizes and multiple cover options, these personalized photo books are the ideal complement to every coffee table.</p>
                <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>" class="tab__button button">MAKE YOUR BOOK</a>
                <div class="tab__check">
                    <img loading="lazy" src="/assets/images/icon-check.svg" alt="icon-check" width="24" height="24">
                    <p>Quality Guarantee included</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="hardcover-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-hardcover-photo-album.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/hardcover-photo-album.jpg" alt="women on sofa viewing a hardcover photo album with dog">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Hardcover Photo Books</h2>
                <p>Digitally printed on matte or lustre photo paper and PUR bound to ensure maximum durability, our custom photo album books are made to last.</p>
                <p>Created by our experienced photobook design team, every book is designed to match your style, and can include text or personal messages.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="custom-photobook-covers" data-path="2.3_custom_photo_books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photobook-covers.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photobook-covers.jpg" alt="custom photo book laying on wooden table">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Personalized Photo Book Covers</h2>
                <p>Share your best memories in a personalized photo album by choosing from a range of gorgeous linen, vegan leather or photo wrapped covers.</p>
                <p>Our fabric photo book covers include a hot foil title stamping. Custom title designs and embossing are available on request.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="personalized-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-personalized-photo-book.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/personalized-photo-book.jpg" alt="personalized photo book in presentation box">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Presentation Boxes</h2>
                <p>Add a photo book storage box to protect your precious keepsake. Constructed of sturdy cardboard with a black matte finish, these boxes will keep your memories safe for the years to come.</p>
            </div>
        </div>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Ready to make your Custom Photo Album?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>" class="button button__light section-transition__button">start now</a>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> reviews</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-accordion">
    <div class="container">
        <h2 class="section-accordion__title">More about our Custom Photo Books</h2>
        <div class="accordion">
            <div class="accordion__item">
                <h3 class="accordion__title">How many photos can I include in my book?</h3>
                <p class="accordion__text">Available in five different sizes, these large photo books can have up to 244 pages which can hold up to approximately 1,000 photos.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Do the pages lay flat?</h3>
                <p class="accordion__text">No, these books are PUR bound so handle like a normal book. If you’re looking for layflat pages, we would recommend choosing either a <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>">layflat photo book</a> or a <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>">premium layflat photo album</a>.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Can I add text?</h3>
                <p class="accordion__text">Yes, of course. As every photo book is custom designed and includes the option to add as much text as you like.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">How much does a custom photobook cost?</h3>
                <p class="accordion__text">The cost varies based on size, cover type and number of pages you choose. You’ll find the price will automatically update when you choose the options to start <a href="<?php echo $this->languageUrl('static-photo-books-') ?>">making your own photobook</a>.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">How long does production and shipping take?</h3>
                <p class="accordion__text">The average production time is 6-8 business days. Delivery times depend on the destination and mode of shipping, you can find more details on the <a href="<?php echo $this->languageUrl('static-help-prices-') ?>">photobook prices</a> page.</p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Does the photo book have any PikPerfect branding?</h3>
                <p class="accordion__text">Our logo and a small code which is needed for production are included on the last page. The logo can be removed on request.</p>
            </div>

        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>