<?php
$this->headTitle('Fotobuch online erstellen | Fotobuch gestalten | PikPerfect');
$this->headMeta()->appendName('description', 'Ganz einfach ein Fotobuch online erstellen. Wunderschöne Einbandoptionen und Papiersorten für das perfekte Fotobuch. Mit Qualitätsgarantie.');
$region = $this->region()->getUserRegion();
?>
<section class="section-hero">
    <div class="container">
        <div class="section-hero__grid">
            <div class="section-hero__left">
                <div thumbsSlider="" class="swiper-container section-hero__tab-activators">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="custom-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-book.jpg" alt="Individuell gestaltetes Fotobuch Leinen mit Titelprägung Weiss">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="personalized-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-personalized-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/personalized-photo-album.jpg" alt="Individuell gestaltetes Fotobuch offen">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="hardcover-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-hardcover-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/hardcover-photo-book.jpg" alt="hardcover phtoto book with family on cover">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="custom-photo-album-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album-book.jpg" alt="offenes Fotobuch individuell gestaltet orange">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="padding-bottom: calc(90% / 90 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="custom-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album.jpg" alt="individuell gestaltetes Fotobuch in schwarzer Schachtel">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide hero-tab-activator__js section-hero__tab-activator">
                            <figure style="position: relative;">
                                <img style="width: 100%; height:auto;" src="/assets/images/hero-tab-toggle-6.jpg" alt="Flush Mount album example">
                                <img style="position: absolute; top:50% ; left:50%; transform: translate(-50%, -50%); pointer-events: none;" src="/assets/images/icons/button_play.svg">
                            </figure>
                        </div>
                    </div>
                </div>
                <div class="swiper-container section-hero__swiper">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="0" data-name="custom-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-book.jpg" alt="Individuell gestaltetes Fotobuch Leinen mit Titelprägung Weiss">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="1" data-name="personalized-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-personalized-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/personalized-photo-album.jpg" alt="Individuell gestaltetes Fotobuch offen">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="hardcover-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-hardcover-photo-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/hardcover-photo-book.jpg" alt="Hardcover Fotobuch mit Familie auf Einband">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="custom-photo-album-book" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album-book.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album-book.jpg" alt="offenes Fotobuch individuell gestaltet orange">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide">
                            <figure style="padding-bottom: calc(620% / 620 * 100)" class="figure-webp">
                                <picture data-priority="2" data-name="custom-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                                    <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photo-album.webp" type="image/webp">
                                    <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photo-album.jpg" alt="individuell gestaltetes Fotobuch in schwarzer Schachtel">
                                </picture>

                            </figure>


                        </div>
                        <div class="swiper-slide section-hero__slide hero-video-slide">
                            <div class="hero-video-slide__preloader">
                                <svg class="hero-video-slide__preloader-svg" width="60" height="60" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#8ba4b4">
                                    <g fill="none" fill-rule="evenodd">
                                        <g transform="translate(1 1)" stroke-width="2">
                                            <circle stroke-opacity=".5" cx="18" cy="18" r="18" />
                                            <path d="M36 18c0-9.94-8.06-18-18-18">
                                                <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite" />
                                            </path>
                                        </g>
                                    </g>
                                </svg>
                            </div>

                            <div class="hero-video-slide__item"> <iframe frameborder="0" id="hero-video" src="" data-src="https://player.vimeo.com/video/569978045?background=1" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Photo Books | PikPerfect"></iframe>
                            </div>
                        </div>

                    </div>
                    <div class="section-hero__swiper-pagination"></div>
                </div>
            </div>
            <div class="section-hero__right">
                <h1 class="tab__title">Hardcover Fotobuch</h1>
                <p class="tab__price"><?php echo $this->translate('From') . ' ' . $this->format(
                                            $this->smallestPrices['photobook'],
                                            $region->iso,
                                            2,
                                            $region->symbol
                                        ); ?></p>
                <div class="stars tab__starts">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <img src="/assets/images/icon-star.svg" alt="icon-star" width="24" height="24">
                    <span><?php echo $this->reviewsCount()->getCount() ?> Bewertungen</span>
                </div>
                <p class="tab__text">Ob Familienurlaub oder besonderer Meilenstein, ein Fotobuch online zu erstellen ist perfekt, um besondere Erinnerungen zu bewahren. Unsere individuell gestalteten Fotobücher sind in fünf Formaten und mehreren Einbandvarianten erhältlich, passend für jeden Anlass..</p>
                <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>" class="tab__button button">FOTOBUCH ERSTELLEN</a>
                <div class="tab__check">
                    <img loading="lazy" src="/assets/images/icon-check.svg" alt="icon-check" width="24" height="24">
                    <p>Qualitätsgarantie inklusive</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="hardcover-photo-album" data-path="2.3_custom_photo_books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-hardcover-photo-album.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/hardcover-photo-album.jpg" alt="Frau auf Sofa mit Hund schaut sich Fotobuch mit Bildeinband an">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Fotobuch online gestalten und drucken</h2>
                <p>Jedes Buch wird von unserem erfahrenen Designteam entworfen, so dass es zu deinem Stil passt.</p>
                <p> Es kann Text oder persönliche Nachrichten enthalten. Unsere Hardcover Fotobücher werden digital gedruckt auf mattem oder alpinweissem Fotopapier und PUR-gebunden, um maximale Haltbarkeit zu gewährleisten.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="custom-photobook-covers" data-path="2.3_custom_photo_books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-custom-photobook-covers.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/custom-photobook-covers.jpg" alt="Individuell gestaltetes Fotobuch auf Holztisch">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Fotobuch Einband </h2>
                <p>Wenn du ein Fotobuch drucken lässt, kannst du aus einer Reihe von bezaubernden Einbänden wählen: Leinen, veganes Leder oder Fotoeinband.</p>
                <p>  Der Fotobucheinband aus Stoff hat eine Heissfolien-Titelprägung. Individuelle Titeldesigns und Prägungen sind auf Anfrage erhältlich.</p>
            </div>
        </div>
    </div>
</section>
<section class="description-img description-img__order">
    <div class="container">
        <div class="description-img__wrap">
            <div class="description-img__img">
                <figure style="padding-bottom: calc(713% / 788 * 100)" class="figure-webp">
                    <picture data-priority="2" data-name="personalized-photo-book" data-path="2.3_custom_photo_books" class="picture-webp">
                        <source class="toggle-img--js" srcset="/assets/images/towebp/2.3_custom_photo_books/min-personalized-photo-book.webp" type="image/webp">
                        <img loading="lazy" class="nowebp-img" src="/assets/images/towebp/2.3_custom_photo_books/personalized-photo-book.jpg" alt="Individuell gestaltetes Fotobuch in Geschenkbox">
                    </picture>

                </figure>


            </div>
            <div class="description-img__content">
                <h2 class="description-img__title">Fotobuch Geschenkbox</h2>
                <p>Schütze dein wertvolles Andenken mit einer Fotobuch-Aufbewahrungsbox. Diese Geschenkschachteln sind aus stabilem Karton mit mattschwarzer Oberfläche und bewahren deine Erinnerungen stilvoll auf.</p>
            </div>
        </div>
    </div>
</section>
<section class="section-transition">
    <div class="container">
        <div class="section-transition__content">
            <h2 class="section-transition__title">Jetzt Online Fotobuch erstellen?</h2>
        </div>
        <a href="<?php echo $this->languageUrl('upload-photos-', false, ['product' => 'photobook']) ?>" class="button button__light section-transition__button">JETZT GESTALTEN</a>
    </div>
</section>
<section class="section-reviews">
    <div class="container">
        <h2 class="d-none"> bewertungen</h2>
        <?php echo $this->partial('application/partial/reviews') ?>
        <?php echo $this->partial('application/partial/reviews-box') ?>
    </div>
</section>
<section class="section-accordion">
    <div class="container">
        <h2 class="section-accordion__title">Mehr zu unseren Hardcover Fotobüchern</h2>
        <div class="accordion">
            <div class="accordion__item">
                <h3 class="accordion__title">Wie viele Fotos kann ich in mein Buch aufnehmen?</h3>
                <p class="accordion__text">Diese dicken Fotobücher sind in fünf verschiedenen Formaten erhältlich und können bis zu 244 Seiten umfassen, die bis zu etwa 1.000 Fotos aufnehmen können.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Liegen die Seiten flach auf?</h3>
                <p class="accordion__text">Nein, diese Bücher haben eine Klebebindung, sind also handhabbar wie ein normales Buch. Für Layflat-Seiten empfehlen wir entweder ein <a href="<?php echo $this->languageUrl('static-layflat-photo-albums-') ?>">Layflat-Echtfotobuch</a> oder ein  <a href="<?php echo $this->languageUrl('static-premium-layflat-albums-') ?>">Premium-Layflat-Fotoalbum.</a>.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Kann ich Text hinzufügen?</h3>
                <p class="accordion__text">Ja, sicher. Jedes Fotobuch ist individuell gestaltet und bietet die Möglichkeit, so viel Text hinzuzufügen, wie du möchtest.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Wie viel kostet ein Hardcover Fotobuch?</h3>
                <p class="accordion__text">Die Kosten variieren je nach Format, Einbandart und Anzahl Seiten. Der Preis aktualisiert sich automatisch, während du die Optionen zum <a href="<?php echo $this->languageUrl('static-photo-books-') ?>">Erstellen eines Fotobuchs </a>.</p>
            </div>

            <div class="accordion__item">
                <h3 class="accordion__title">Wie lange dauern Produktion und Versand?</h3>
                <p class="accordion__text">Die durchschnittliche Produktionszeit beträgt 6-8 Werktage. Die Lieferzeiten hängen vom Zielort und der Versandart ab, weitere Details findest du auf der Seite  <a href="<?php echo $this->languageUrl('static-help-prices-') ?>">Fotobuch-Preise.</a> </p>
            </div>
            <div class="accordion__item">
                <h3 class="accordion__title">Hat das Fotobuch ein PikPerfect-Logo?</h3>
                <p class="accordion__text">Auf der letzten Seite befindet sich unser Logo und ein kleiner Code, der für die Produktion benötigt wird. Das Logo kann auf Wunsch entfernt werden.</p>
            </div>

        </div>
    </div>
</section>

<?php echo $this->render('partial/quick_chat.phtml'); ?>